#ENC[AES256_GCM,data:0bCYLBIEH8tDFaYfAGYa2wqHPu1E71UqITCLZI2LlpgdALw=,iv:9IaJy9g4O7f3A1QR1sQNSCgRAoM1wmENZM2LYSTxeA8=,tag:XTIDQBHUejUTSYMbTe936Q==,type:comment]
#ENC[AES256_GCM,data:9leuytoZ232KzX/L6aWyMykAg539NNc=,iv:L9617y1ZBNtlU0/FB9SXxJc3Bs/rjHBs7zU/R7ZUAFY=,tag:y7WwdKFHjhclfFNvlpF7EA==,type:comment]
zurg: ENC[AES256_GCM,data:lKs=,iv:K3k7KxvkXFNsyqExoyG18mVNP7iZMv4cqKnHLfjQtsA=,tag:w++AHUOxFAPKC4HKmA1rsA==,type:str]
token: ENC[AES256_GCM,data:ytcN2SlUW0IfYFyYvJJ2HP6dNurDK4babAKKXB6X7TeNQcuMGCX3shITU31QltiABCDRiA==,iv:eXFFr5XkCyqz8bZwwdgWDqdL9BtEKS8cNUrp4d9bMwI=,tag:XR5SI3SWcv0VK/+VrbSb2A==,type:str]
#ENC[AES256_GCM,data:plVna/eY1c6eLrtyfi8=,iv:ZHbbSzwwQCPojrHuzUkfobmXU8v4pgZ0wCYnIkUFubs=,tag:6AEdo3Aptrv53sT93u+bOg==,type:comment]
host: ENC[AES256_GCM,data:eYu0S/mOaA==,iv:SwbKMiDEBlpsWnplJZ3d5A7K6i4xMDMs3AIOUrw8eUo=,tag:M6EWsoNZU17NO68U859XFA==,type:str]
port: ENC[AES256_GCM,data:Ljdscw==,iv:4JshYGMm5Uc6ZkN/4nSfeg4djvCJNtprG1MN336kh64=,tag:cjPlWbc0tghKWkLh05v2Zg==,type:int]
#ENC[AES256_GCM,data:ba/vSAfaLiipr65g3dEsSSpCLd5Xet1OkjI/eRbIVMKdeO/OZ9D1Mn65S4L4GQ==,iv:1jgjldqMwPW0Ra/OQH0ba+vrVvzZsXPudwMuuipx6r0=,tag:paQSptwKNsZuEBU5freFhQ==,type:comment]
check_for_changes_every_secs: ENC[AES256_GCM,data:+K4=,iv:FAZPdsDOnQL5u7tb2NrWze1Dwc6yR23sQ3KrUly2lSk=,tag:Q3OY+4ZLHY8apS3QqFUpEw==,type:int]
#ENC[AES256_GCM,data:WS5yHv7iBUcZIDn0hPABv7wApxfXjgvAHdkdWw==,iv:tps2nMGjXeftlWGzkwEweOZQ6awNONMOOpKaOyUAZg8=,tag:e9sIX0qA2o/YwUo9mhk/ew==,type:comment]
enable_repair: ENC[AES256_GCM,data:q4RDcg==,iv:EvuaC0bhdQuHRb0pICGidNpNvVnWLiR1kpkCEgdLZZY=,tag:ZpAJ5prchf15sPrZf/P+1Q==,type:bool]
auto_delete_rar_torrents: ENC[AES256_GCM,data:T1BPOg==,iv:YHBUAxkcjPMIya5RhtxCXSCw0R8PDpocs7t6tQyNZkA=,tag:68ohaG4GCgBeS5Z5Vkk2+g==,type:bool]
#ENC[AES256_GCM,data:JlntZovGaBn/u+nQn9GoYG+VAAs732o9UDmSFZmSkh/yw4uXimpcBZe+PxUUb7OMT8D2uw==,iv:mdVQC5cNtA3VgOHY9b0UjhUcmJdpbwk2LdkZ1PPoyWQ=,tag:wjQk4/W5QjeXkQTN8IF+vA==,type:comment]
network_buffer_size: ENC[AES256_GCM,data:Cg8LMPp0,iv:J8K42voEu+hqAMSLvIguHIZXzFcLsMVXhyQ3y0eehP8=,tag:lDa4FqtulMpJ5wOLBSanJg==,type:int]
#ENC[AES256_GCM,data:z/okB5Gl5R31D+XEJb52T8jhwUM337Ldt0oa38Nxe8KIWZEdyZra+EvhHeZmXjOzrREFDIKZF6wW3uwJYw==,iv:d1lYlhJSwM3OzOyVa6AzP0W0WJUZEvZYo0MG3XZHADA=,tag:4jnQeDj5cJxO6R4EB1fuNg==,type:comment]
on_library_update: ENC[AES256_GCM,data:KfX59/j8GgrEntC8VqW+iwiYAKJ1SSEKMhp3PKxcdlvSayIud/LGHa3tESe4cLeMfubCcIsSdzGi3aJKv/uc+A==,iv:pvchMb8NsSK2wwuuFd927kiBjZVq1/aNlBwYOEgNs0E=,tag:xsCkY2s++nNe9N0lcURqfA==,type:str]
#ENC[AES256_GCM,data:x8VodwMOi4lqfFbNjKE3kMgNYcXEO3w51ZqhWQ/Pyau7V+akP5TGR2inGVmmLPxIjXzviEI=,iv:FfFch2+GCusRGbYqVprDZobOKlDcdeIg8WPZEVPjyjQ=,tag:5hkaM765icuyyKkj4xrK6w==,type:comment]
directories:
    shows:
        group: ENC[AES256_GCM,data:A+sb6JI=,iv:NlNyCwFBRABIanw2aWA7R5TXvTyWWz9gvPPKUB3Uc7k=,tag:7HYG9IEFzWis5ISTwDMucA==,type:str]
        group_order: ENC[AES256_GCM,data:7co=,iv:odO68ENbHlgT5nuBK0c31UG0J7LhhIGTCpNSeKWUjJk=,tag:fmRNYWZn2auwF8T+iliWZw==,type:int]
        filters:
            - has_episodes: ENC[AES256_GCM,data:psGGOw==,iv:hDqIAjk8RnwSozZpqZ3ECibrXsqwrNLKyBhbJL3d8DY=,tag:SGZGqykPkP7fpV0edcl2EQ==,type:bool]
    movies:
        group: ENC[AES256_GCM,data:dUCJgV0=,iv:9Yk+ZHw5nqFbdNeio3MIADLu+OPSyBmd4VNDT79cosE=,tag:nplG2J6hEbVsdxMchWRfXQ==,type:str]
        group_order: ENC[AES256_GCM,data:Edg=,iv:Y+GWGSn3o9iedhZRvpFdq4IW4wgvV0zZiQ/WmSTSt7o=,tag:PqoEVg4dxqxcPsxTPHDVNw==,type:int]
        only_show_the_biggest_file: ENC[AES256_GCM,data:byCGKQ==,iv:qWd4c4nks1I2rHKEcw25zEgAIbv6WiE753q5jKoJVpc=,tag:u/DIu828kR+PAcVylLuQ7w==,type:bool]
        filters:
            - regex: ENC[AES256_GCM,data:U5pxBg==,iv:4p4eMuxAkToNeK3XIlG3Yb7c/vjAPd6wLWf+DlcqP00=,tag:Ph9CHqY2oxcCpEcWJ8es4g==,type:str]
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLc2VVanlWYW9tSkxQalhE
            a0REeTlSKzFocjFITUR1L3g3MTNJQ0xTVVZJCllrYi9xQXk5OWpHamhQN3FVb1hN
            WSswT040c2VjOXJvTmRwZ0pzQVpiVE0KLS0tIFkvdlZRMWllU01UR3VhK0UrdVln
            aFN0NFdLUmhQa3F6bEhKd29iWVpSQ1UK2o0UlVC8tO+CrGyaAjjnOMyhOQVxBybH
            f3xOUFJdhXI5WIMvt6Aw/oLkDEEiGnvVN/RCsPHUeMtnid+X41yg3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T13:42:51Z"
    mac: ENC[AES256_GCM,data:TaYvzZJz3xyM6unC8gp5uWJo66UamCbbR2CbgPVZCBGfF5A1b4QbheVKfBvs7+W5/HXOAA+vX/g2p4pEL0KBVv7dSNdOXxUwC0jeo7I7MdqEl9cTw6STMPciwti3CM8A1LeVh8esD6IRNIrnqn2sCU2//nTVcqZdkQzc+TCAHEA=,iv:v4LyZScekRvcEyslZ8C0WB0x+20rtvjbTuEEEcVnVfE=,tag:QvVaCSINNWatxcbx/fs3ZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
