#ENC[AES256_GCM,data:p3LwAU8/81bBd+rSl4tIjS5b9Axt8fhrSel36TFR2BnSMUk=,iv:0ns7r6ogXUH8YcaagG03kb4JK5T4ApE+RrreM5zYd9s=,tag:phWjkVleyee0N15SMpFB5g==,type:comment]
#ENC[AES256_GCM,data:zeZ+UtuFCEmfPf+jHRL4IVVmJ0HBZfk=,iv:fmze/mHs00YfgUgtkZRTYwvBNc/Eh+GgcjHcWLhBNTI=,tag:YKat1Kx4w+cxsUjFpCbwQA==,type:comment]
zurg: ENC[AES256_GCM,data:Rw4=,iv:CX3kuKixa7+oTHoWWY06d2MtkSTY2ReiKElmXLMRIJw=,tag:R8QluGs1T+6lPmsgXuLWtQ==,type:str]
token: ENC[AES256_GCM,data:aTSF7fJsFVNaqFGNPb0vebQClBFw+epE70r3kJLAaWJ/opKVQoRV5Z0PFteSNI9bLzwtQg==,iv:NGE+biINotzjeD4POkUmFfH7zymzx0c9ie/GZG356Oo=,tag:u3Q+LiaFoj1+FJV+J0WYaA==,type:str]
#ENC[AES256_GCM,data:jlcnYZKImOu2XdZjB78=,iv:F0/+S6cGiEbju10isAH/HKxcaH47q13HOnF70Pmgcvw=,tag:24PhrV5sDPLYydS1ca3rvA==,type:comment]
host: ENC[AES256_GCM,data:u0flBvGtLA==,iv:tlQ3UKWLlMTgLlkN7OJEvTNaXGk6YrEX/ZXDldeKMzo=,tag:1dLc10YIG8cI09B3tNt3Sg==,type:str]
port: ENC[AES256_GCM,data:ECw4xg==,iv:UDdpPK175EpAAuKNSG2oKzNkZGOZ2TXdSlyIXi9/hmk=,tag:JVJFMxA9WKbuOi6o+QavDQ==,type:int]
#ENC[AES256_GCM,data:AGuT4SIUk2h/HC/6qdoAeR2zVbqVXY3MwVg0fyFR1i3L9vEhC6fcV40DVLhxrg==,iv:AYCbELOjop1Hd1ldqV9nfFAAem0MuNCe89pDPvVZg64=,tag:fs+eEZ8sC/vpIsZTAXIOpQ==,type:comment]
check_for_changes_every_secs: ENC[AES256_GCM,data:c4I=,iv:VT6/u70MvI0cAnyzuNCz2rfGzjCRy8nMpxVzy82RwoU=,tag:fEtkOAKi8wdK397Nnuekew==,type:int]
#ENC[AES256_GCM,data:4iPQeUa9Jqph+TSgDyQ+Qjj+XMDqUY6t5BZNFA==,iv:0VLReR0iLIS2RZ9lnozTHL3tDHRRrfL5S+XJb4M9CsE=,tag:g0mQJ6pqBG38nHerepnFOQ==,type:comment]
enable_repair: ENC[AES256_GCM,data:nFnZaw==,iv:ilIKM2Wnr1JC6JZrNmuRrb9/WK8iunzPjoWAU502uAY=,tag:90FIglEP0ke7mRGshscQMQ==,type:bool]
auto_delete_rar_torrents: ENC[AES256_GCM,data:ejKXWQ==,iv:Kv8V+c2AoCS5vJWluOceqk+QCO3qe2GTov19iHGl48I=,tag:5A7qbsjJZOOc9IVoC6rX3g==,type:bool]
#ENC[AES256_GCM,data:i7Rh47z96bN3ohSsUBkIzq91ln1bQJPAaK885lRfMYPWycEDtVvD2AqdAvt1gUpPLO2khw==,iv:27c33JsWfZmryKFRRXON0UZ2uWisY5rWZWJo9Qt2yVc=,tag:spw2c2Nkp7A4Kq7BFGGA1Q==,type:comment]
network_buffer_size: ENC[AES256_GCM,data:ebrIg+Wp,iv:1J9Arsn1kv7yirQhdTgi/HHzD0oCI+qqf93C7P1vupA=,tag:GQQoG4Lfh60MLIXCTT6qbg==,type:int]
#ENC[AES256_GCM,data:WvnbeabUF3dBm300nkYSebo8ruxQT2dqKGZUm4lR0x6FB/FfccDZzfxzr2kjGH6EtfpEWnP0PoycrrHM8Q==,iv:dNfVkuzf8YoiBThfwr1pE6l2QXVOnSnXSoLAEXZtIYo=,tag:uolCixZtQvezlhWPecRdvw==,type:comment]
on_library_update: ENC[AES256_GCM,data:i2f1o2EFmVeQ5Hyc54D3wuRuohwFwwbpz+9kViNIGozhVt8udspQ4cnw50TqAuKLav9zBQbQiJhLtKIOpQDa5Q==,iv:FMos3fS282sAgqA+6US36KlATwNvdSD5IOtnU7fHIx4=,tag:R8UHm+c2aHBjCGmzXV/UAA==,type:str]
#ENC[AES256_GCM,data:YceQOo60wSeEHYsKkkrqk5CUKpGGFMbawNDXve4qqKaMHzobhnMqmAQ+rkLJHOngECA/cF8=,iv:C8NxroZGN4NSoplbOOMGmW/aO+6eauTaTFQ/3g4yGLg=,tag:0+8sxKMdpilZ3u4HcNKBIg==,type:comment]
directories:
    shows:
        group: ENC[AES256_GCM,data:7Vqo6Cg=,iv:8wi30c/pA6SoASsOuiOp17lVLwyJA+vhWq1HiBgmldE=,tag:z4wNawEVxM0Nkh6WcbqdMg==,type:str]
        group_order: ENC[AES256_GCM,data:m5k=,iv:8+a+c02h8juZFpONbJgyNmqANEPYgQ/gj+5af9u31LY=,tag:imr8biQI9E3zduEzzjkxuA==,type:int]
        filters:
            - has_episodes: ENC[AES256_GCM,data:fJK0UA==,iv:vE9SxMo+sWov0dhaUt13ajnvWy3WHcRB6YeY2tAMtHg=,tag:lz1RRzKL25FTPqtTXrmEIw==,type:bool]
    movies:
        group: ENC[AES256_GCM,data:BfO4g3w=,iv:S+e8XrIl0k/HkoBlVja1DyCblV0UbE39N7H7h89F4JU=,tag:nHIQnujM5fWEydJJovrpmA==,type:str]
        group_order: ENC[AES256_GCM,data:Lvw=,iv:POiINwv8geRZl0eTeBw51sZD1hjh5a8wsC0AUZh+lcs=,tag:S5KQD0sCy4x/BHH3sKwdXA==,type:int]
        only_show_the_biggest_file: ENC[AES256_GCM,data:q4E6zw==,iv:39sODvzPRjlrQGNboiuXWxtoVJVEGnpVptmia+9s4Ek=,tag:8nvEUEc80DQYkhPUfpaDiw==,type:bool]
        filters:
            - regex: ENC[AES256_GCM,data:dQU8IA==,iv:E/kULxhXC1UtXttQhxNfg3t28mZQwIr8XTCqgpZNnBM=,tag:5j6ebNWJwl4ibFo5fSfUaA==,type:str]
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcW53NDlhL3N1OE0zcmcw
            Zm1HYWxXVllVSTI5WE9TWHdGbUg1cmFsc1FrCkN4cFUza2ZPTE15QURVMFFMVjMx
            ak5HbVljQjdJMzZhQUx4TWJNZ2pzN2cKLS0tIFVmUkxmTUkwTzhlYXRMMGFweEdv
            eDVRdXhJalM4L3FPamcxZ2FDTk5uclEKSnubEwmf0exGoXR9hbYVuSrwhuTx0yhO
            GtsvoUHB0HYbyB5qjjgOhQsML4iNMQBKTpVDAKp9v0HbPW1XrrOQnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T08:52:38Z"
    mac: ENC[AES256_GCM,data:2FC7XH0C/0Nhy68ufkjlfaoZVs6uSmrSMiKbhHOQ6nL8/sPe0EWKA1CMzIR7Rs0NLLAIv2x+fHYHAL+kMjHdZe8kRXmnOAS0ABkfs+pG2QEdz2kGrZm8n34bl3CEgtD9gkl46lOYcKPEnmDFnG33gu4snYnP0OW0LdsrTB5r0qk=,iv:SbyR4AA4K5Jtu9ssYYMPZpBeMNSjdGlTHpxpv9G9L1w=,tag:wafDEDc2N/cIj+Hu9GtcTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
