endpoints:
    - ENC[AES256_GCM,data:xQzPazU6iU4i2BaGfKBcJd9xNil8714=,iv:Q+917xgxKDd4IH1L36Ra59dnfEodVaDeXsQMVtpSCJI=,tag:Ld3tVd7zq7PPTTADlQaQXw==,type:comment]
    - name: ENC[AES256_GCM,data:JUBgtw==,iv:tq8oMFJLHctIXwQEMwXtqbEhhJwx8hJoK5CcYMyDkk8=,tag:5EZwlrpOGg9WJ8QZ895uEA==,type:str]
      group: ENC[AES256_GCM,data:YWyzFPo=,iv:waOhyrBi/lzxMfIaAFx88Pv+a+tFzEeovfIrsxqS12c=,tag:zAS96WF4YqkaZCDoSuze/A==,type:str]
      url: ENC[AES256_GCM,data:7DI/wzeCuLoYitJcitjDrev6NZ4yY/Rsh/K77UraOj63l8gT,iv:SIR+1fd7RENK73kk4+Hd97HuqGAGXRv+NY3G4Bfes7o=,tag:7GS95ErJ09YQPwOiHWt5LA==,type:str]
      interval: ENC[AES256_GCM,data:6XIS,iv:9oUbaDoSL8c1FpoHCuVu3KRpyQHk0XqOlnHDY39TasY=,tag:DJDZOM1NL47hhIV/kK0nHQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:AcW40vvorlcVULPoJrSa,iv:/xcd+KahtWdrnCQazMVa62SNhAsYy5tckJbD49WAREg=,tag:kFazQlRdagCR/4mohzWD4w==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:+8XWwCQOog==,iv:MVh7YpL9mfrQk/DT9YnDgSpFHn7sjbNKVaRNwH+gjI8=,tag:+NtEck9bsYttZMyWtJZxrA==,type:str]
          enabled: ENC[AES256_GCM,data:S43cJQ==,iv:A4saZ9l/rCNJFB9/HOSPcwLPa5XHL5JQwBkzVvGpqdo=,tag:AFHCDbliELTZkfMnXnOKsA==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:XIx3oQ==,iv:dYlFZtSRPMiNhpG9dibwrg9nLvTDcVDSvXh9CfxPH3I=,tag:Yb0KS/fsr5pZQG91+bMGoA==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:/g==,iv:H4xsVAY8csK/vFyA7FkdBGYwcOPnqrzwkM9Dnd2ez7s=,tag:NfoqAiM5fQLbcYGxl9CzSw==,type:int]
    - name: ENC[AES256_GCM,data:2Q+Q/41b5oFgAHxFec9dBhR7KlxmnCSyeg==,iv:FUokOJsi3l/O0mhoeVmcHh6D5sbsWYWl5Mo81HA9WsQ=,tag:N+vWzgLGKvLoZH3/Hc2+Kw==,type:str]
      group: ENC[AES256_GCM,data:6c5hDUk=,iv:OlqH9r+zgOUWsUQUzrsNPuFj68DGIu+UzDQa2DGrfow=,tag:EHg4SS7IKohOnPVQ7I4mhA==,type:str]
      url: ENC[AES256_GCM,data:yrnOCYGjNDJHAKIPlo7J2i0DcQKfAQw=,iv:jYDNLXQLUkLF7uAGeI/3R2BmlgJX37UFYoRt4hrdxUU=,tag:YGQ5NFRV7uCcuNw5/AgcNA==,type:str]
      client:
        insecure: ENC[AES256_GCM,data:eHRplw==,iv:yzwbcF3ReQjbHjhosWMd3fx5wg/7eO9iYbfFxAUbx7U=,tag:xDomt/y7O2zhyn4SWiQNIg==,type:bool]
      interval: ENC[AES256_GCM,data:UqgP,iv:Md6ymVdg482LhAQlGM2Z24l+B54mevgbo/Vg/qyHdA4=,tag:HCswNqWNHyYBOxdrE2GGKA==,type:str]
      conditions:
        - ENC[AES256_GCM,data:9coFbSGaEEBVJOliBcqU,iv:6hA33lyDcnJ1D7lnmCsqWAmHaohBejT+nEbMpVeNCvU=,tag:i3xX6Uyk2MgvDspY6AZraw==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:P36p0LTKYA==,iv:z0F4rHFqB6B57sHJra9xSc2pe8s1HyNMDcDLeOXjBkU=,tag:tipWBMUaNI5H9373wFnJEg==,type:str]
          enabled: ENC[AES256_GCM,data:1/GqnQ==,iv:E0fH48iT1XhHITT3Tj/OQOGInfi69Bq/G+tN8uglxOU=,tag:9Tszq3nH21Jf6aDjZU3/9Q==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:E1hGAQ==,iv:8KxNdUGRAhgzbpLksVNKrxaxaygg2JddEKvdFomWNDE=,tag:tkiSaAw+evxOOy0eZkMkbQ==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:hg==,iv:mefn0uSpgD+imxxnOHR/bMtr+D0Kt0ecBPmkMtbZ7Vs=,tag:vap2W6/0KVfzSH2N5nYCHQ==,type:int]
    - name: ENC[AES256_GCM,data:v6AzbmeMk+0=,iv:+/JCKBz4wMha5fdHgDXCcipWHos8/PYyM8A2RT/KAP0=,tag:4BZcBdjaI/n6UuN8XfFFuw==,type:str]
      group: ENC[AES256_GCM,data:OKC9MSQ=,iv:84xIuvPyL2AVLooSDI8ePhLYjT1MQh43nrFEDW/do9g=,tag:VSO+N1tfFTp9FeWA1pmtfw==,type:str]
      url: ENC[AES256_GCM,data:kcyESVh3iB8TBnWWLHkA6O/Oz9Bu,iv:ctFE38M1iUj/N5OU1HOQ93dR8Hd39hvSKzlwruX+ZcM=,tag:5qe2V7OFTdHQOkl4XAYguQ==,type:str]
      interval: ENC[AES256_GCM,data:gaNn,iv:NzSmVVO4BwPvMnMUnEUwDiJvDcyfX012cd70CatNJKI=,tag:ZYL7Rb9NnEWfLgtk5sMLPg==,type:str]
      conditions:
        - ENC[AES256_GCM,data:kYb+VC+wbkrXxPtP3ubB,iv:4pkCMHW2QBtMgv0bGAPtEYJHoWSlEyRKkKjAHg4pJUw=,tag:X3MYHTN2IoTmsFRUzcZfqg==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:xA8xo4Z4iw==,iv:rIp7dAblIbQV3rgwF4cgRUHYcBGH5Fg2+WQJNpGoqHc=,tag:hLEByh9y6oJzfx4wK9XNaQ==,type:str]
          enabled: ENC[AES256_GCM,data:K1yrPA==,iv:VaoQcWVRRs/ftJnP2jlRNSh+KCmibyPDtSbrK8S9Y/8=,tag:E+QYJUR2VwZp0usUXgReeA==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:ipz3NQ==,iv:d1lb3xMFfznH8zHZH+w3ivfMEYgAEKtdK4EOQvTz6kw=,tag:8Q1pJArImPu77lzJg8i99Q==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:rA==,iv:QfAhYRH8k3jYpfCkGUwwI1Q/MRcD+TqrDK4uN/YPKFo=,tag:3DEZC33gE42FceaYhVZh0Q==,type:int]
    - name: ENC[AES256_GCM,data:448N+Q==,iv:7+0v4QTXnLuDtBt9jH1yizFR3fupEUdMB+Hl8pMahHk=,tag:+8apb72iOQWTYEXk4CSNAQ==,type:str]
      group: ENC[AES256_GCM,data:ikU+nYk=,iv:s5Ly7X1CVGh4d6/W5uC+SMQ6z3N1L/9XAtNWlYc+Z60=,tag:ixur4XCZubAP/zIeZzGOGA==,type:str]
      url: ENC[AES256_GCM,data:PEsbTV96It/DjjKFLeBe0Cxj0JyQ,iv:eNycBQmgbP+aBKBI/owI1cRPIArYZbiq4MCuY8AUmas=,tag:WbwjnCZAur7Unj5j9jJ9sg==,type:str]
      interval: ENC[AES256_GCM,data:nl4f,iv:p4LHz3d45RhuBib/A/fRs222e3Y0tly9GaRAn/0Q2I0=,tag:PW8HI/AYl1FxOS+KLPWLLg==,type:str]
      conditions:
        - ENC[AES256_GCM,data:jSqRYKwthNGVGyfky6g7,iv:DxyYt3PpisX3BpCd8DPP1GnHOi+x7oMneZ3GxAwJbYs=,tag:Xx9CiaUJ6NNIk67KM4+p/A==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:5ZNFBl8yow==,iv:bilLpLx+QwRSM58UTlzONu54ORIqThzz5tG/bakLd/k=,tag:FLo9stcykFfXZ0JUlA6XmA==,type:str]
          enabled: ENC[AES256_GCM,data:Z3oI3g==,iv:poOcx9k87u8ms5uiuGezQJ3G3idZHmtU8pX+tIaHB3E=,tag:6nCKaL4+ouGMBgYII6VAEA==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:iy0IbA==,iv:Pei3pvcKmwRXNBxhtZAkag6IsOKoUNMK2jyKpD0+Cno=,tag:f7rU3FKPgis01ExcnmW2dg==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:4Q==,iv:E3RCg7nFIlrRoVnpBhqhlSjFxBnFTaZwDYDPlJ3VC5Y=,tag:JKvYUWWyX7Al8MUBBrG2hg==,type:int]
    - name: ENC[AES256_GCM,data:p8bEi7bEtTa3ew==,iv:XJVhegcXt8LTRC5qyyeq/N8yBMWPf4uR2uW8AxT4Jhc=,tag:/wFV5D5ne6Rlvzvsi5EUCQ==,type:str]
      group: ENC[AES256_GCM,data:xh5qngKSk0vQugCz99o=,iv:HwnWn69WqRunJ9nV5lK09b6pbZSFSeEC1DCL8fXPXBM=,tag:Yep3Ul0KooA0tOMWqRIQHg==,type:str]
      url: ENC[AES256_GCM,data:lxhoc77SHZ25bSI9gwqd0C3UAKzHPdxbTYREBg==,iv:d1ORwf2RzUjGXWs84Q5A1BFBmJhcD4HiozBfwna998M=,tag:A60nbbFRnzfTnkkl+97eYQ==,type:str]
      client:
        insecure: ENC[AES256_GCM,data:l+kR7g==,iv:TKSE7lGz8NaXbBsiY+dpUau5VXwi2mgy4zOYkU94gng=,tag:LNPaX7zznuRk/iS1nEGnhQ==,type:bool]
      interval: ENC[AES256_GCM,data:r7JI,iv:JAOgjCbTA/p1oEEX6OIxF4QNv8Fv6xmsJzf8DrOOs0Q=,tag:m2QoaiAL1+iCA3leJ6nRaQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:5EOUq4G0YAi7x8ZtnDGA,iv:UUiF5Ys6c2CTytne9UaJFxeCPQsIhenhM1NFQjtA6rs=,tag:intgtjrODcW3+P/jM5/PHQ==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:YhEi/1jmbQ==,iv:VsidOoxPGbhHDHbVjLMQY6pZg+YAesZFMNKfL7ohcdI=,tag:9yr5EiiGcTbY+2MH8gnRaQ==,type:str]
          enabled: ENC[AES256_GCM,data:g25S0w==,iv:dGBzvCWYw/kF1a5fDCNpcJ1tf6PuQNVTiCU5P20tuJw=,tag:nUl+0QQDCvFc2jsVJmBTjA==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:X2XUFA==,iv:a2Ged8zwkieAikul0FgiZlwi1Lc7aXoHzWsSFc20RlA=,tag:WFsVyR1MbS1Cfvqr9EaRGA==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:JQ==,iv:zShQ+ssmlARoA32cY22V78lRB7f423TyuzjPG8Pfdao=,tag:0NUvhtO9r51rEE2AMlAvUQ==,type:int]
    - ENC[AES256_GCM,data:dOxDDFsUkUObTYEqNA==,iv:2tcSbFFJnj/W3hn+0vjpzN8XgtYRNqNxtGSoUxTNcBA=,tag:ulpLSJlNnKki1SxQ9dxQZg==,type:comment]
    - name: ENC[AES256_GCM,data:euS9KsuNkVKBqnuWrdMQmifu/bRL,iv:yoChsHt43Cq8Y/EH6/SMutEhtDMeYYxOOiGBrAZM27k=,tag:KJRebxTXuycpy5JlHTNTCw==,type:str]
      group: ENC[AES256_GCM,data:1bYTYg==,iv:fDCsJKzBDJmhKUmZ5efH5fzf8ccpBGv4PgpcxeLFba4=,tag:OzU80bfc0FGFOxdgVSMl+Q==,type:str]
      url: ENC[AES256_GCM,data:7JCla2GE933i+ntXxE+b,iv:JUbHIKu8pFFjH+3bfvqgCzWB1guRlewa3sLoeaziFUo=,tag:FoIW7cCrkNeZdIK0R7M22w==,type:str]
      interval: ENC[AES256_GCM,data:q8Q=,iv:hM9csai9dWLOdAZpYfNoMGG7n5kWgSJOLRNiHNUsBGo=,tag:HD6v8vUXAxwB8fDza2n97w==,type:str]
      conditions:
        - ENC[AES256_GCM,data:Rl+J4WS/8hrpp0O+gc6t,iv:KjTt9KJqTRri/QhPrGNb/kGjepM2UmapXdhVHHzjUQo=,tag:lpwyhST0OfOq/CHeUQImjQ==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:FsoRCQBXPg==,iv:w6vBszu55IAFSPFj4+U3bZvy5rx676HRg68v7rp8nCA=,tag:mdQn2Ywo1cDkWydJuJFfmg==,type:str]
          enabled: ENC[AES256_GCM,data:i/hX7g==,iv:QbYbtt8bpHOuouUUEVb10rRi61uFzx7SACWpCOmTrLQ=,tag:if/P9n6Li+giQ6pdFpatGQ==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:WH5EAQ==,iv:H0ZP1W+Tc8Qthyh4RKv9KCl2t6/WuOcZNIseK1Yq6HI=,tag:QtM0wz0YNe4DhGnJaSWu0Q==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:Pg==,iv:vMgj91nIc8MxOPLBxbXoNNrG1YUp+6FFlB5DP0VOc7s=,tag:5Vj4OkH+owk8H++508pv+Q==,type:int]
    - ENC[AES256_GCM,data:WsSJdpumO4AMMs2zlAd+fV9LDZA=,iv:2rbnmdTt4hqRUPHJgBXmHgFxETl6E60vh1NaeLaKQYw=,tag:vVntaWuKOZIgGe52Vr0ytw==,type:comment]
    - name: ENC[AES256_GCM,data:eBxgHN0q7dPO,iv:w0xxcjZ2U/tOYug2TlsffZzasgC0uUrwwYWiXBDQVME=,tag:fmKiqcuN8H1hwzV+XBIBcA==,type:str]
      group: ENC[AES256_GCM,data:d+YiNyjOfkHS50Q=,iv:zkObYamdkbOLRFTkKkDIrTIG9WOY5/ycwXvmBtf89Q0=,tag:PdOMmdzdkZf6FeinFkECCg==,type:str]
      url: ENC[AES256_GCM,data:5e6wL3J716Yo6nZ7hGLzI7lqw7IFiDinDg==,iv:wWCm65+w6WJOCVCefprxDlMQx8/4kMibvDQCeNJ8Tmc=,tag:Jb7RUee9ROkybM7w4jdzrg==,type:str]
      interval: ENC[AES256_GCM,data:/lUS,iv:YziTkEvwWunK5qOHAD8ouIJDa3dn/sPl8DhePC1vp5o=,tag:xXa3T3EcIQ5jgElIimVkDg==,type:str]
      conditions:
        - ENC[AES256_GCM,data:2iAKgVC9RyiCFTXrLjP8,iv:03b25sMfmExIXhf5gRhwWeN5/qzOzZ//u+2BCkLItBk=,tag:zNjw/IFsy0GbJTv4O/O/ZA==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:gU2ESTkpkQ==,iv:tIXipo7im5D3Q7DlOeDRa+ELI5+q6K5M4/YB52jpMXo=,tag:MEcIZU9HnxeLuEyR1gyYFw==,type:str]
          enabled: ENC[AES256_GCM,data:D+S1Tw==,iv:72gxZrf7eruSBN7MjW2n8iRNVsaNPK/3ap6zQ95RPZg=,tag:dxymPIIQvgItGNBixSYDsw==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:XfhCYA==,iv:XjnZcF0d54JoWEQSs6C199uOsxDOpUGa6lcQ5JHIHS8=,tag:tEKM+JVP9Njh1J3dJJZiXA==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:Jg==,iv:EAJqZ821YN6ewqJtBg6saTuaRIoF5opzHAxxVF9VNaw=,tag:PD6O3WszrvCewsPUh5EEHw==,type:int]
external-endpoints:
    - name: ENC[AES256_GCM,data:ywqagji9,iv:Q3eTm5sPo+JtyLe/xsqWRgY0MUuqYZzeio8xjDcpFrU=,tag:fvyemQFldLJaXAYStC5YXw==,type:str]
      group: ENC[AES256_GCM,data:Cf5t9WlQsEw=,iv:8locug9Zaxntc8TuDI4tCeYKSGBgufisn+Cj748nNXU=,tag:UFLyy2TDUnTlb62TuuB9vQ==,type:str]
      token: ENC[AES256_GCM,data:WCuWqpHv1N9a1d3FDSapgKYbYnVwinhGNc2NfatuYy/CfKuUrNDltuwGVQ==,iv:XrQnZfSgxQWw02HFbABnYD2TYCtzsUf+Fh5RY2bZdyQ=,tag:RLYDlrKlKFTXL/0ExORMFA==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:Smyx0D0Tcw==,iv:XyTUv+cH99YdCz9M0S1aAOF2/AefiF0LWJr/dgwLO4M=,tag:4VELsMni03xvzql0sjuHTQ==,type:str]
          enabled: ENC[AES256_GCM,data:syJJPg==,iv:KCl3jTebVsH4aZ31CFpvj/Rbor/CQF6NBf2afoM8RYQ=,tag:NOGuoLRJCRxs2EvCkzlwIw==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:Qd08dQ==,iv:oaegPDm1kmJsD8LAYKfctPHswT163tUZlO2MkvkcW1g=,tag:11clEtafFtBTxts5jCUCvg==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:sg==,iv:kz+nXTNa0d67ZANuZ4+rlKAKyJnteGeO2jjvF8QxDG0=,tag:9Yvk0qWXe82yVGfMNJjkXg==,type:int]
    - name: ENC[AES256_GCM,data:vSddjuxdDMrpi9OO,iv:4xVfPV54TwY2KQGaAtv1uDuq2BLPqa+iMVXf5V29olA=,tag:1lFSfzOdhSZcqSmZQWTdNg==,type:str]
      group: ENC[AES256_GCM,data:BPfhq+HeyNo=,iv:NgyNxnUxGQOt6nYb4KUTJQyog1UbiRMfkywuNkh/MKI=,tag:utXdJIG36ZjXFQsSY/TKyw==,type:str]
      token: ENC[AES256_GCM,data:a0sTx+Hp0tSz8ULOaJtuGG4n+1lKp8CFZ7s6tnXE/6tvQ91VSb3Oymm9Pg==,iv:tR4D3iICJYfkISRTFW0ghuDX4z2kSjN2UvrMB7TuNyQ=,tag:LmXZPSPXHJvRqPe4I4UhZA==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:D1RQ4fXV5Q==,iv:I6mxVubOKuMN19Ou+2UxVBV9tFo6mR6wSXs+NrYB7eE=,tag:grznGg3NSM2Y3tPNhgG8qQ==,type:str]
          enabled: ENC[AES256_GCM,data:M9NzuQ==,iv:KB0Up9fDq+mnW59cOe+OMq/Vnsrj+FFu6MxoymXSxfw=,tag:nmwdK+qawo8chf5Uz7HF9Q==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:rTSk/w==,iv:SNBTXH3NyT1tY9BpDSMJMGEqpyi1kZD4rTl1gVYE8yI=,tag:fAGWh5112quAUDOSO2Q3+w==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:kQ==,iv:CdISm1twYnfKlvcPSVL4B4OsB/wrO+B7w9U4iGOTlGc=,tag:FNJ7Y35hji5QgwghDlNnCQ==,type:int]
alerting:
    discord:
        webhook-url: ENC[AES256_GCM,data:xeecexOHOPZChbcz00oK3UMX+xxUzawt4HxeM5UaLk3RHUCZ1bCrfVcxi47cYfn8orqgPrCEFQIEZo24rQsHlqPJO9JHCeisIgyZcXRd/jMFLMDVh+d0FkQgE4niulQBY9SErIecskIGfcjaut6DAyIsfiuEf9g8,iv:8yVQ5azWi3hGe4LF0mqrd4E6c7BRT9KG2amI+jZXiOo=,tag:Pp2EwhWqyqscDYRqTdYh9g==,type:str]
        title: ENC[AES256_GCM,data:FZbxyehlP3XsiRTH,iv:OXFtOngkeXx9l0GZwPloPB7kI2xSZMYhNFk8Rj32a8Y=,tag:mLh30/l/9nJOZ9xYNGowmQ==,type:str]
        message-content: ENC[AES256_GCM,data:l5P/W1r7RW4+vwNx9O6mWaUOGbHt,iv:HvQPhKNDtQaXgXFm4jCweSwKp7/q21bfBBLRPBG9OAM=,tag:Olpkzyp51OcuzO94Jg28Sw==,type:str]
web:
    port: ENC[AES256_GCM,data:PR7ffA==,iv:BiNLgys/CoWAVOJXLbX4P2KfjckydTvlC+JJ6gghzlM=,tag:YLXMAgpY4NJ+QtWvxPg8nw==,type:int]
ui:
    title: ENC[AES256_GCM,data:ejsaSBcp1CSX+b1xBiY+0uSFA56jqeVLP+w2Aw==,iv:Ra/ANhlJC61zuYF1nbo3GEtjoLvOleu2OpTNjQ1mxto=,tag:1F4fqskqTCiFhIUvJ1ecUA==,type:str]
    header: ENC[AES256_GCM,data:cieXbU8083ke/QOwaJCEKRfXFc3Sjj2a6dLSIMFz,iv:fMUAz60yT1AASeHFlUEyLXfC6OfhOQVqHaAjKx0ezVE=,tag:K21TeahL3sEVpmOZGm0azA==,type:str]
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzcWV4cktxWW8wY3J3RkxZ
            UUZLMk9FRzVMS1puaHRtZmZyWHdRRHA2TlRjCm83YnJyVlNzMVYyZnVNVHNaT3hp
            WE40T1kwZ0drUk8wTWFJMnllMFViZVkKLS0tIFZSdUV5c1l0bUtOQVJKdldLaTkw
            UEM5bHRrNTVubzZwTlZEVlJKaGIvRVEKVEo5nXWWHRSTZGqb3ttfcIoXwlNoCD8t
            XKMfbKI91HRlRcf3wC7VwrnLzYRpV9jSjZFQ9r3GomrUOtGyRSyY5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T15:57:38Z"
    mac: ENC[AES256_GCM,data:Vmz//ignS8saIU/FBWA5wiRfaHQ0IeirpS6pyeFRVuQ1B3/L9UxtpNNGOLrbNyHsxKAJgP8PWdOH4JzXJXKiBlFgksynwoXv3vq9NHE5LER2w9uV0y03FLNbRXd3/8pIoVcW1ie5etUDNo3RcwP7di7jQH7rcJ5TzWo5+z9hdBc=,iv:pBFCUYsENY9/7ifyAb57SjNUqu8Rr5vNpE1ojPKJq/8=,tag:QJsfEMDQDrw4GXMbFEww4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
