endpoints:
    - ENC[AES256_GCM,data:6haXrodh3/W18s74A/fkDnGEu9QAaBI=,iv:BKPrMCyqf+ieAWaYdjfOMuRsT8XqPKsJCkmzHBZNNpg=,tag:vJLjUJcpnSr5WEqxYMm3lw==,type:comment]
    - name: ENC[AES256_GCM,data:5f2QPA==,iv:vBYl5ZtlzNN/z3S9d9cMgIRcUTZhiYVimd/wRTFxnFs=,tag:9p0GKZi6IzepNtSPBRxroA==,type:str]
      group: ENC[AES256_GCM,data:t7z7Cl0=,iv:BLjJ4Z3crbgExeC2/8utB3hbcAlXkO73B+BLqg21TOg=,tag:Xg6SdoOcia3+vSe3d6bI5Q==,type:str]
      url: ENC[AES256_GCM,data:L5pIQOtjhT8ci7kf0CJc+3OwtYfEeA4p+MqnHvG6WOiaholM,iv:TdyknVFl1FbG8DXFVvy2j8RcQkH8lQPgueXERoX1c7g=,tag:7gyzNeavEWH8sYHZR91fNg==,type:str]
      interval: ENC[AES256_GCM,data:v1ie,iv:QSi8wFrDEU5FHt8603tXIeyi9dJcVUpTWm/pFJvTUyM=,tag:DiCiUzXlRpGa1fDKw6Aluw==,type:str]
      conditions:
        - ENC[AES256_GCM,data:JptKgyUJu7exgUGrbd+S,iv:qHa24LOVhOG/PbvAcrJCujHG5zHGIFTFw/bpM0+zcl0=,tag:TsikChrnepzDBftljfY+Yg==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:cJmhM1PR8w==,iv:x0G6TYlpYzgiYKHNOmjoMCm37RvIqWvd0+FSbtILpJM=,tag:vw0i7uaWULGgjpKuWkkvlg==,type:str]
          enabled: ENC[AES256_GCM,data:ITF2Zg==,iv:GSkuw6eHlhjUIfvZ4VFp92hAllek7x54gZ05cZrd0MY=,tag:ibQ4kTnBH7ZyecLG8ADoow==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:J+ENwA==,iv:XUIkjZz3cI/I87s7SA5WqodP9KX7455DOTJ1QNrU72o=,tag:wnFqAl682cWc58a1wUgEHQ==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:zw==,iv:WW2wW2zxaq5qq7+zo4YXDV1Hq/nm5RaRBrqM8PTEQBg=,tag:ao2rdDSN0fV145DdZYaRgw==,type:int]
    - name: ENC[AES256_GCM,data:BuBF2cUTVJ0f9DQ84YIuuAe/FBjQ/HVqmQ==,iv:yONfmeZbx18MyWdNkUt4AN+et3iw2ndHeUESFMm8kSI=,tag:gb4mQFVZjwyzAIVNS7IJyQ==,type:str]
      group: ENC[AES256_GCM,data:NSY4pyA=,iv:rutl3pgw4vGzj8olCQ+o4VGwhgY07+IxyHqTsSNj/9I=,tag:7eer00XER2dum0Jk4Cw/Rg==,type:str]
      url: ENC[AES256_GCM,data:XlnTszNY+F4v8jn+LaY5GML3gHYLiWI=,iv:w8ZqLquAYQ7WZCFwlv9yymQbWcnRIKGAyJHH1TpSP5w=,tag:8aBpIlY7stwb/FDS0egQ2Q==,type:str]
      client:
        insecure: ENC[AES256_GCM,data:si24ww==,iv:zFqT98AZ5LPCnieGF7VBqA0mmZOx75hONnVCcqpyLew=,tag:rTeWKaxmS/9AyoASCioZnA==,type:bool]
      interval: ENC[AES256_GCM,data:KoNk,iv:QNpOsFVy78CEs4GcccAAfnjx2tGQ17Y8oBUQzQbDu44=,tag:lHhgUBQTshGOnCtZrnaWuA==,type:str]
      conditions:
        - ENC[AES256_GCM,data:1ACAVul4AtbqWrMeH/4w,iv:cqmi64bOJ0bEkyZEYVBr2BwMrl3gZIDDzrK9l8jWh7g=,tag:hG412RgHq2sML6z3/51IfA==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:hNcz0+gu0w==,iv:nw5dHmvfqu3VmrTnhowa+WqSDJGNXCJV4KhnhtqMiJI=,tag:Q1DIKGyKcu5fcvp30XI/rA==,type:str]
          enabled: ENC[AES256_GCM,data:Fgrpvg==,iv:VWMU2mMJ1z2Mq9DgKxzsYIr7dpm8RF/BxUNq0WSzzSw=,tag:+0sng7q0gt/tqoZnaLA+nQ==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:Dg6GRg==,iv:P47iKQzFIbRmFdH6g5VHXSQevWBgFvWB1pa5iPr4z1M=,tag:ljth6XoxMo4uwmyMRcCv4g==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:3Q==,iv:joEXHsWD850QnMOiHSOeYIThNZx9wiNTm/UBvNXnew8=,tag:gY4fd0JkYlZBzongwJahuA==,type:int]
    - name: ENC[AES256_GCM,data:mrdcu8qU+QE=,iv:5L1O/c11ZlVDVvb5GXiv053sWEdrT2avYyKU58QtaOc=,tag:3B0sRXva5Hdx39DxKP44Fg==,type:str]
      group: ENC[AES256_GCM,data:irNbswk=,iv:4cBLNXu18AEsVxR64ZTaOG2I/1G3uhu6Kr7oQw7scgk=,tag:SMJOJGtSZhcEamQBdDZ7Lg==,type:str]
      url: ENC[AES256_GCM,data:rVunNi2MVGLV5QkMOKurlkkC++iF,iv:HVuu3a2N7/pRorY+z8mlXPE+kZXn/iL0xSxrIR01mdg=,tag:QIyc0kkgrWWKsMIPZIK6Mg==,type:str]
      interval: ENC[AES256_GCM,data:fcNx,iv:oRpPowGiCdFiYuNyDZac5PtUc/ePpzApaKca8UElGc8=,tag:NM4edylcCndMwEVzLVh1DQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:RmVLWmmoNnzk+QHCLG+w,iv:nRENnh5s6XV4hRVF3NY+SVJsyvqUdD04hRlKHM1nKa8=,tag:BZazYbfyRDtoXVxC56AoQw==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:OZ599ZimKg==,iv:Yfm8oBAO6U/AYsrumPDUdFMF1bqFj8x8C/38c/gN40g=,tag:eilBzuWueC9Z766bGaG58A==,type:str]
          enabled: ENC[AES256_GCM,data:7UHSXg==,iv:mhG2I4csikgFBnCXnMjaoBzFKawQRNCqcF0Cn6/5tkQ=,tag:zIfZEMnZi4p/2/YSPK2kaw==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:ZFE4jA==,iv:tZx9BKYPb1Wr4hD04svn/5kbQaN5Rofdf0M/PIEmFW4=,tag:p0Ltu238f/rQdo1HcTlu1w==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:lQ==,iv:Mf//6rpFFNY5rXMTfvX47R+1UfZLg02LghKGmy14qQo=,tag:jUgl4ytyIXvzrYvAN2zdpQ==,type:int]
    - name: ENC[AES256_GCM,data:QkUgPQ==,iv:RWbW9fCZiES/DGWON3M8VAFVgazg8rTMw61shThP/hs=,tag:5Y8Cf1QSI8lBMr7HNddRtg==,type:str]
      group: ENC[AES256_GCM,data:jyMn3zo=,iv:l6L3TLBiipjYd8n3aEwydqPMSqVXOCBqkt4mtqvKaxs=,tag:8ptwgTsCEPXIpC1+cozhRw==,type:str]
      url: ENC[AES256_GCM,data:eCvHcrejeUs4mEzK2JhWRTHA9dbJ,iv:w4q6GhSNaDI5inLtRRfefsuypUsKt1lIk0G5+r5mCF0=,tag:L/UxsGvFO0U0v4noBnV9hw==,type:str]
      interval: ENC[AES256_GCM,data:cg6b,iv:e/oZ56Bvoz0a+McRRPfCqgRpDq/KOydQdr3ww+WoEJw=,tag:oBWFtXbUPa60BryNOpGbAw==,type:str]
      conditions:
        - ENC[AES256_GCM,data:EV5zXueDANro9NECUw3v,iv:JSUZTjiFrk05wWBL4qme/Upp0zZGR0g1a9ffwSeGebg=,tag:0I+zu5mZvABZiClsLUPy9w==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:5T2W7yRKQw==,iv:Tk2YMmrqiZLp9FC3UDKQ3OdNdnW8Sx+adBaaweTHJKE=,tag:xKHOXtKAl0mrEqxP3TN3ng==,type:str]
          enabled: ENC[AES256_GCM,data:nJ7Lgg==,iv:hZecNfFjKhiSI/W1qTr0yz9KHK+YN1o/6KFg+FdsqBo=,tag:SORs4JUUaiI+DwVw5+SZ2A==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:SxAtSA==,iv:TlHirTQjV+ZJGR/J/TQuovwYw4+ASXXvPslwrMpaLt8=,tag:TXHlWWOqfjFH+VAwHlZ8Lg==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:CA==,iv:jqfcrIreQnjWpBOI8KdEg9snygOcR+k26763LFZE50Y=,tag:COudGy0Q9JH7Nctv83iCxA==,type:int]
    - name: ENC[AES256_GCM,data:htKI9pK8jtGD4Q==,iv:dX9gTaZ31b5u7FzaFGorU/epj4AVt8wlg+GksS2QG6Y=,tag:DHq5o3ohnYCyh7TN+4iFKA==,type:str]
      group: ENC[AES256_GCM,data:uLVbU6o4WYPTXZ+//Ek=,iv:1GEsqut/WPjGBV/5AjeaVLD0CyhQn0rDEomsHeE7kds=,tag:P2A5Jgc8yZkiElE+uHGQPg==,type:str]
      url: ENC[AES256_GCM,data:e1yrLxKahFGKYTDaQQ3L/EpvMSJi7GQEqzgThg==,iv:1gg6QcG1n0LHOXeXIJzWKYoAXhb8dmkOKZgFb+AyxhU=,tag:g/YApYcbojQhaqkxf+Lw5A==,type:str]
      client:
        insecure: ENC[AES256_GCM,data:ZcPb/g==,iv:qRb0PWCjmjCjTOx55B3Q1ALmez2sLk+QWOA0xafhnk8=,tag:Ud9CsnjKvvsQcb4bKYEbog==,type:bool]
      interval: ENC[AES256_GCM,data:9tCP,iv:bUzUZidYJi3RBUNIzS58LDB9b2Lmw0DwHwUIgtTJXCA=,tag:nwTzT1OFLyBPqrYN9lOLjQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:rTkYBPLFNx4RMgTLPk5A,iv:gKtqHFy8fjgJtdHQTg2WmAre18FSa/rs0Xz6p/tSlhw=,tag:sxEbFQQvw1NbQh6P1Z9uUg==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:1voplGVwbg==,iv:44ovD29RHDSTxBXFzE+vRoN97J/zRmCF3Pal4/sZtyw=,tag:5kAcmofq1agg5QBosgeGRQ==,type:str]
          enabled: ENC[AES256_GCM,data:hP6XrQ==,iv:F3NOT44lePdzRJENyELR1FRhff/nh5LyRm08+PtU+Ng=,tag:7dpAzn77MjvD6vTmmSZ5rg==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:sl32uw==,iv:66YxdhsaAN7rUM02BBqlNrk+WmfTL+oaE0uTeHaohNU=,tag:x2PM6eWEKIMUSCzY7P4J7w==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:3g==,iv:UagEYIpkJgVWt73C41IJER9qnQsAgxxMQSRITtkv0Xk=,tag:skhKMhm4eHXq+0a/LESBgw==,type:int]
    - ENC[AES256_GCM,data:8ubgk3lwRMuO9ZK2HA==,iv:741RdExf6qwUlUlj87NRCwxkUL98dCW549lgxpoqisw=,tag:4ugoq0gSTcSU/NlCLf6sRg==,type:comment]
    - name: ENC[AES256_GCM,data:R6sIIwHMQuekJHC2OEXvnP3JlHAB,iv:vRQIMyMISxVlNsvo38sTmmVMKSvDQgZhpG0ybhnvdPg=,tag:RusqQmbto4EzMcRDZZXIww==,type:str]
      group: ENC[AES256_GCM,data:K6U1CA==,iv:QIjiXOtIUR+jrFxJkiNv0z/3X0ngYUYU9JcJn3J7JRc=,tag:GpLk2WUQeHTzo5b7G7F2Cw==,type:str]
      url: ENC[AES256_GCM,data:KrM/GXGINEw3OWoISaiu,iv:9YQAOn3bQNkuTga500zUXgwEn7oK8yykdeQcBxvNBcM=,tag:Q8Y3iu4wPwlQsc1EaddiRw==,type:str]
      interval: ENC[AES256_GCM,data:eng=,iv:imdDvYnABqwzmzpSPgnqN/vh1pP7/sDqHGLcfayeXLo=,tag:bDlMYxOlQ7XAX0MkIpZxqQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:su36UVHwnjShFfRZlbCS,iv:Vy/kmohi0vuAveoBnsa3ffSw9bnzmpOJjeYXmFd3zw8=,tag:3KuVZSP+WXrw7R0/x3Iycg==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:1BCy/tXHcg==,iv:t/MLrC+FHoNQ6ZDlVHJuWGSBQSYFITBky3xAh3v5rUA=,tag:89RfedeEbaCoukdHGy/qlA==,type:str]
          enabled: ENC[AES256_GCM,data:B23knQ==,iv:fS59apKqnkAX0/AhKPDZKPQJxL96foeZTMTT+XBYNJA=,tag:ZFZqj1ElPEtdaPbMDAumNA==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:QO/ePw==,iv:nrw700lIy48fNhf2Q6JianQyMMHIqpP5z4AqD/yodjk=,tag:ZzfGoObaIvBRJeSnvQS4NA==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:7A==,iv:QThtte6aLRKM91Rxcckf3dQJrk2kYOdu+GHmatK21oo=,tag:eSDF360k3NAmyjir4soUKQ==,type:int]
    - ENC[AES256_GCM,data:2BgrvFrM4AFekIr4USkn/pvVGcA=,iv:uMtfwdCkpBVgLpl5PFtaPBlkHKVKskIDWbyY/oltQT4=,tag://XXkK4P1r0+SxYPuuhKpw==,type:comment]
    - name: ENC[AES256_GCM,data:Y8IbA+/BCGLe,iv:iOz6Th4DdDnqxw66nLpQIVRjEwjpksQqiKU7C4asGZE=,tag:QPAzdxWpB5ZOJzgkqSh2Hw==,type:str]
      group: ENC[AES256_GCM,data:NZae8ekjKct5T58=,iv:VEMNgd7FaaK24FWmhXvt+jCuBDtwNkq8P6E+zRBGtqQ=,tag:RdwhL1LSOJ6jTxpQCMwp/w==,type:str]
      url: ENC[AES256_GCM,data:bExqf+uyul9i3B9yyvgUX5XWr06/2NTz9w==,iv:8iLG0PTwH9oJHS0pEO6fGA7xy7uQBLYrn3VizShvdkM=,tag:IY0qM8iA6SatR4XfqjTDSQ==,type:str]
      interval: ENC[AES256_GCM,data:bzRS,iv:y4IBkL/h9gvLGUXRtTm3hcK+7XNum1vcvoW4HBTW8pY=,tag:FojgXAD5NUY76ngefn+o2Q==,type:str]
      conditions:
        - ENC[AES256_GCM,data:A6p9nA9MXLvZqpQbg/XB,iv:WX/j8P5uhLWZ6KNfjmoNMKNdqWCOJRskE2a09Oz0UeE=,tag:sE5197X9JupdiuXpMSIraQ==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:K/3b0vQAVA==,iv:OUq9L2mIKVVHzjPWHzszPM7Nf1eVhN+ViTIOsTZgWNw=,tag:MW3UCq9tL20xM7dVfSZltQ==,type:str]
          enabled: ENC[AES256_GCM,data:KjknnQ==,iv:ftLwxyHtJ2OLZqrGr1zpxnFEFewyFjfxTTFWo9lSo1g=,tag:vgqK7K9ptf2CHS7ULYTXYA==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:MuvDIw==,iv:cDhXuivS63piDYEP7l45hwuFr6qYlvboG738NTyJjo8=,tag:ZBbo0wnrq7xynzTg+vAxhQ==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:ZQ==,iv:GQ1diXHUirJjtOsiY3ZWyK9Bh7F0pCcIvI3Snb4DrQw=,tag:nLj2/xciE4NuxgZuLGCcEA==,type:int]
external-endpoints:
    - name: ENC[AES256_GCM,data:st9icSjR,iv:sSxuYwp0TU10iTSj3hcxMPPUUJCE7yQfAT5RgKJYQew=,tag:VYirZsjoIWVAvP+89EpJKw==,type:str]
      group: ENC[AES256_GCM,data:7n8oJK7Ysk0=,iv:MYTuPL7JEvc1q4SgfZ78oGEvIN4FtTRcZmMxAU5ANCA=,tag:+WX8Vyjojhxs/ndM5EHVCw==,type:str]
      token: ENC[AES256_GCM,data:mCqSmr0JjPzxxowICrA2vJVOT0p0T6d4rRy/nVKhKHDHsTJNvKbKXey6gg==,iv:oFoTQr+q4ysruHP5ScakMR44kHXiOEklSAdrFfW3H+U=,tag:U1naec5ISQgu4MZNutPJsg==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:OjLunQm3bg==,iv:4MkYkRSeKD/9252tp4YX2LU1BVVpcy2CMblQdcWWk4c=,tag:Nw3y7UKRl5lJHwmSz4rZ1w==,type:str]
          enabled: ENC[AES256_GCM,data:Gko8RA==,iv:v2EWYlI6+R3cBGSkGuNTcZIGW5eiOO/fYV7FpaXB9gk=,tag:6ZxBv2RiWPxj48Go4LE1mg==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:t+ZOHw==,iv:ZdeiDhXhSx4DckuKg4Ajf6utZtoia2y+1Xov6rPANF4=,tag:uB5VEUgfMDmCsxBIjcY62Q==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:4w==,iv:nBmJV0XgKb6wXgLvTPy2TKndplxk+O+biBabRMtl7/I=,tag:xNiLLwiuxGYHxzIUhYHDig==,type:int]
    - name: ENC[AES256_GCM,data:YwvFJZheUHs4wE0v,iv:382SqSFwJMxIL1SFiv2rvpshkf+AYhyw/OcsBfEXmXA=,tag:1+Wl4kyT48cnlM4/2T9AYQ==,type:str]
      group: ENC[AES256_GCM,data:CUkKwI3jOuo=,iv:ksmJPp9imjBpulNz4rO9rTCpOxdrzaX0q/WpulE5ewE=,tag:Z1v+0uB9Rztt+ZTq08fF6w==,type:str]
      token: ENC[AES256_GCM,data:w8LbtUpJtHBjPiimhkXUhsudJlhVcrvU8Bt4x113Fd/e9hXk+/OLa2f5/w==,iv:oCLFOZGAG4FP8ZXL4bcploHaz+EOzLGZH08jM+x1LpI=,tag:jgRtWoKxR47iQCpOD3WGvA==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:b9ey5h1VFw==,iv:UBkiUOrAREDRPpWazZsVc6U5ePg2wkNYjBvgYBbs9ds=,tag:Q0rC5Ikf8ETCfQ1kkEFyRg==,type:str]
          enabled: ENC[AES256_GCM,data:wsPX/A==,iv:DxWJXFNihiK+N4D9EUUs/FOPism9D0DBHDKPrnakpqA=,tag:vDJIH1Pq5O2wfIjtMpo6gA==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:GLe6rA==,iv:zJ0ZFOcT7YIJ0X0AZK/fV/7zxZGoYYjHd/yXc079WO8=,tag:erkxJPUCt3hlz/wp+v1X7Q==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:ug==,iv:s2xc0X9IbDhz8fznUZBPIsq19tDcmcdbZmyBRyJsnDA=,tag:HC/hommuCE4NZMKHRt31/A==,type:int]
alerting:
    discord:
        webhook-url: ENC[AES256_GCM,data:adDMKFNT4kfz6y+e69T1U9a3iwoVz8RQHU6aNeLFzZieorGAB6gLSRHuhMCeEjcwVZA7hja6warqextx50LlhpbXclh3w4Zl00FvcNcVoRX4cDCMswvBwVNe7HwKcNGCyZsYQ5/toAPYninhBGSbE4GgKThKAGBp,iv:hT55QIkbCuuucSUoOR6MJ3jaRte2P3ZSW2nhfLHFrUo=,tag:EBXylVLXl3ROX54WI0yOpA==,type:str]
        title: ENC[AES256_GCM,data:8zwZqMJ0cF4qvhJt,iv:DTjKa1Nfq2cC94+1g+TbM4wz+ln0Reh5tlq1QFegtnM=,tag:pf6YAevb1ngg7FoVqzoB2g==,type:str]
        message-content: ENC[AES256_GCM,data:9694OhLI455cnPYSZXYiyI61XUWB,iv:WPiDyHOAkoc7jus0D2rnqQbgEzbSEoedhFGkzkBEB+U=,tag:GDRTL6GHfb71FqfXgrXobA==,type:str]
web:
    port: ENC[AES256_GCM,data:zl0e1w==,iv:yZ+qBxDVNkQrqgOAREEWeq/8fKaQNz5eFlhj9FeUwqs=,tag:c53dPvlKyLW6Zsq4Ld5Skg==,type:int]
ui:
    title: ENC[AES256_GCM,data:ATt0kHpeOSxvU/zLexPx1mFoqY8siaAvTY5IxA==,iv:RYm/UkIftvJLw7HeWxn8gf2vXhNK9UnmXtscxpjkkHs=,tag:e3XvLmDGsVwAmemMiuUkpA==,type:str]
    header: ENC[AES256_GCM,data:kL8dNWmKbsp61lu5UWRcQa8wXCAMJsOQVPUnBXfg,iv:aWutJcJWPM5OKqylnWwVLQtMIIJx1WOOXKmSxIDt3l8=,tag:Q5S3kwQg0sPgr80ofYVIQw==,type:str]
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRWtPazE1RUtYM2tHblRB
            YWJaaE5TZkprenFtSnBJRDF5Wk1qK1RzT2l3CjNObUgxNm5GZTBzZ0JhblVzRnRp
            c2xZSWp5OGwrWjhjdWh2bi9PcmpPdlUKLS0tICswWjlqUjVVbjdpNzA4bUNGcUoy
            TlV1VGxRdG9VUm54OGdjSDg3WVJGR0EKIXH3QaVs/uqtsxJbbc5OuLKAO7T7oW3I
            1ZbtLLLJuwCOecs8+dUqbc0syP3YzyTpx7Pdq+fYkCShK3cU8IQaqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T13:42:51Z"
    mac: ENC[AES256_GCM,data:c3xrXHa7pt2vD1wVCUrlmRNYf2GHW9UoZ5sK+U0161kgge1filGRjh2HWqP31/N2yAIL2BoLUzsTngeEAcE2ZbhXUryo1OiibvwNFr3UmnONr8lqmH6oxfLVHPV5z/7/WmTZbX5dW9QD8hnG9/g1CB1bOtinauuyX4zJ5IYItOw=,iv:+/dvqC8gjqUxKgEMWhlp2IeAg/+3XPyrTU7VE7hOuJU=,tag:WKEOD3qwYWQucjyMN6GrZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
