#ENC[AES256_GCM,data:a5DKccnk6+ZRdoJdX+tI2OAHVHcy0vdqiv41I+wXSHUFG827oE0YqN00t9gXaKpuN58XSn4=,iv:rTJ3xf5aF1US6JISNlJAhtDt6l8VZuvmiXQS4ggra6c=,tag:I0hgvI92FesSpRIluyn/tA==,type:comment]
#ENC[AES256_GCM,data:uDl7oP4OWjmkYffo1d9OMu99ZiqLZg3WvWQMTHhgFn3gLlBSdrY9k6yZd6ymxOehXtWuGo/XQrwygyT435XD+Lu9,iv:qNpzX1C4ot2yj70Igmnt9wHdt69Qb9dTScQBsfUH39s=,tag:FlRm9suD8riZJrLoaqRdcw==,type:comment]
#
#ENC[AES256_GCM,data:sLpr8lMBmNIpBaRgU/PVqkvWuSGrHJ++ZNeXqb3xkVHuyxRwJVzcjOqMt+wzfDIwWvgYKu5CBqD8QhWXDPHJ,iv:pFRwGjvkcu/QLVce7a2i2VacjfYJs7HYAzcruocwCZc=,tag:1HBGOxumK/wdTUc5WgAJtg==,type:comment]
#ENC[AES256_GCM,data:rEfiOTBxkV1Vu7HJ8KNNJnoNB2BGA9nY1HAY2jQ2g11lUeXhVv9htQgn,iv:mG3fN/k8YZdy1Fj8v+0N1KvZ+hHrsfPKY9nH7Ea3DJI=,tag:gF1cEVtB5c7WUtYgPbEY0w==,type:comment]
#ENC[AES256_GCM,data:C7uOGke+98uBvI61NDT2nB8fegab4I2gRY4QSCu65ywlNPthRac3J2hMdb5ePvGvuSf5OA==,iv:4/7Ir1DyeOXsvSKmS7JlgoEviMBiAZwfE7w71nwQ3p0=,tag:9JPI6Fp3aVklT8/cRTM0NA==,type:comment]
#ENC[AES256_GCM,data:YuINmNFuF7FJcD7GlpL68eZ7Gx8sF1bvxuqxMPw+YVhollz9qVdBJbF+pSN7UxGM9vDN7XPh2tk2lZZnUQ==,iv:/hFGrQo2bF5k3R551hAAWHTSLiqluWQ3rCvomvUsy2s=,tag:cRq194q9SpxGwg6Nmvjbww==,type:comment]
zurg: ENC[AES256_GCM,data:dVU=,iv:D23CGpR1OgpLmvvhKy6drkFdGXlhB73jTegK1XePy/8=,tag:CEL2C3Pih8sthI3cEaU/1w==,type:str]
#ENC[AES256_GCM,data:MQjfF8g3ksHqSYGFmdWVLNC7eJaWAA==,iv:+Rlj+OJlEfHI/h4bSmUncJ1qzL2C3485ZT++5V3X2EM=,tag:F91EbFtnuM+oTUQoNmxj2Q==,type:comment]
#ENC[AES256_GCM,data:CjdGxgmCj1oUirYQxjlRpAS8zFeg5VMtAMjEIr1/CTy3u0JSt5BY820P/45Ie9+Zfg==,iv:npy36GRAp91Ci50EkqF3q2tjiZjhrMYOBGnyVo3u1yU=,tag:sWVcbVXo2mQ9yf8ei+frbg==,type:comment]
token: ENC[AES256_GCM,data:inJ1IBSKn7oIqc9dXaVdeV5iV33CkKuqgh9ghJvyA85FMCU61iRVu+nweI7UnWgtkzlmJQ==,iv:Z5XgLcHIvZaIHw12O4h0vfKjIMxb9HRN2c3fO6w5zs8=,tag:INhmrujrUVqvf6Ug2ewreQ==,type:str]
#ENC[AES256_GCM,data:0sQ9c3SAjw+LjQzniRxcJm4PDQ9D64MIYqlA5Q==,iv:KXNiTMIoXNDopuK0aVi56tylSCsxZijvkBG23ObReqg=,tag:U+J4/hloezGbJ1RK8epKMg==,type:comment]
host: ENC[AES256_GCM,data:dGV1/4ojNg==,iv:3miA+mmaE7aW+in+wlM4F15pQUKQp7/MUy8hh45qyEs=,tag:QW7/9EXbMt5XWK+HSj0ybg==,type:str]
port: ENC[AES256_GCM,data:8+Vr5A==,iv:GCirQrSYO3Jg0QiAdg5aNLZ0YW/7PnNO46kwUZ7PXp8=,tag:uogYb+Zd7dPAwSNjQaEggg==,type:int]
#ENC[AES256_GCM,data:usuUrALM0LKqbYfQpTSqhUDo7OYgN9zBtzqCVJY5h6kU,iv:L8jJIq21nRrQ07fb1GfPHNrZY004w6CdiGU44Trrfsc=,tag:qtJgjY7AJJBMV4vwnVK1EA==,type:comment]
check_for_changes_every_secs: ENC[AES256_GCM,data:WB4=,iv:Umr6RxxLWTkbuNAOfgSPoL5vkSQWyef1O/cG/VlR6oo=,tag:fHR5Etj8DFMqvcWudb18eA==,type:int]
#ENC[AES256_GCM,data:s0zM5DxrgVxdSuOmf2FvrsbdTGC8Gx3x,iv:ZPFJ16rIn+p/9hzv/ifl579xLn6HNT0LDiyhIs9eTpQ=,tag:vnV2ZXxOa6zFnOQaURUosQ==,type:comment]
enable_repair: ENC[AES256_GCM,data:i/G3TQ==,iv:RmC3+Z+0rGffQtBJdp72yTPyULPu8oeeAKs6NbuXni8=,tag:3tb6Jlk4z7wdM/LGmRhqgg==,type:bool]
auto_delete_rar_torrents: ENC[AES256_GCM,data:v5eIEQ==,iv:FeJtkOdzBkXzFN2l5vzy6ov22pYvkuIh8qAa/pGus1A=,tag:v0DDaaraIztDeBWbQD6l+A==,type:bool]
#ENC[AES256_GCM,data:DK6B6PdjArmS4kG9sFQ9KGuu4kCniv0BwM3s7KXW9ufsCULf6hQL3+pH4Pv+yaXT2xI=,iv:lSdMsTPnZhA8U3iwVfaDZKXPHDe7T/IYlwwr+49BSHI=,tag:tSPV+Wufpw+Thc4tKt372A==,type:comment]
network_buffer_size: ENC[AES256_GCM,data:luSUdbAZ,iv:1c3lTH5Gm0wXn7LcZqvPY4GBwlVi4FFFd+kuXJSLBsk=,tag:Bw5x1fW0z78Z9CQdROV9Tw==,type:int]
#ENC[AES256_GCM,data:VAz+DKn/1J2LuECd2lgD8w7JzOVz+mIr8k9SE/+17DBURac92EhnDBe37fSAvdEtuhtNlo8sF22Im8Yl,iv:dgg0XcDBXXseYsFvFSoWHJ4PKrHYsjABw928oap88EQ=,tag:JuUHlVyDHgeZ+Rk55wkf3Q==,type:comment]
on_library_update: ENC[AES256_GCM,data:nZdffLCJxrtUs4xvMJ/kXXbUb81/MIAhaYwn0q4MTAQHw6jPwNt0+HAzhExZlU6CQPjbj0o=,iv:qukIAEN6A8YtR+BiQc0BPo6KsGUvOGvr5t3aakY2BA8=,tag:cZzKKPUxXfPCbITuC2E9Lg==,type:str]
#ENC[AES256_GCM,data:gCX3GtM1E7UP9fOE31I83C+wjS0XLHE=,iv:aZCCSrza4yIujwy8IexSzISWeaySA8bDXwQeWkOiPW0=,tag:XYyv5I9vGLPigv3djc7wEg==,type:comment]
directories:
    shows:
        group: ENC[AES256_GCM,data:ymq7bM0=,iv:+4VceOw5s7FxY5PJnz98O2G8ky/NJJE2NoS85oYfqDY=,tag:+kZX3X7H1lgX7OO/r3IRsg==,type:str]
        group_order: ENC[AES256_GCM,data:XQU=,iv:isaD43x4AVxhp4o0uX+dAtLlvyvL+YQzi570AL8Cm68=,tag:pqUBjndaRMZB+sS7k+9BVw==,type:int]
        filters:
            - has_episodes: ENC[AES256_GCM,data:yZ9t3Q==,iv:WPSctfl8BJDob5HI0aAZhvOHFeSgYdMZByaXASEqfyQ=,tag:OI8kan81rqoGI3fXfOaSIg==,type:bool]
    movies:
        group: ENC[AES256_GCM,data:n7smrto=,iv:CrbJp40eBELj629gMeE3of4qzb4FuV+wiy30QVEBvWg=,tag:GyceH3Ts/0rAwiLFZ73KOw==,type:str]
        group_order: ENC[AES256_GCM,data:QRM=,iv:rBFJcJS7E5i3Xudj1q41KBFdxrZA67WS0eMVFPxjwrs=,tag:bPX5BfvIv5teuGZ4hTsD0A==,type:int]
        only_show_the_biggest_file: ENC[AES256_GCM,data:ED7zhQ==,iv:pUVPiJ+C6dnkaQiZE/WxA7OsuVQBX8uok/xYKhdPZQc=,tag:P0zafU38i5yls7GQdresHw==,type:bool]
        filters:
            - regex: ENC[AES256_GCM,data:tmQM9A==,iv:pNRfZMm5rF6BW96kSyNt6hUp5k5A3o3mFvgJ4FdRU6Y=,tag:wZUzRt96LfBd2DUTXfdgsQ==,type:str]
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYjBMN2M2TStGY0tZV09r
            dUNCa2hOZk9vS29Ia2hyczVCR2Z3clhTQ0NNCmVQTFBFb2syVEdTSUVxWFMzcTRT
            REZJeXArZkFGUTRJbVB0RzlkeVJXTEEKLS0tIHFlNW9ia3FKWGRURlVUOWVqS25i
            Z0w3TkFPR2txYjJBMDU0d1FpRU54akEKlMlQRXiIkD2OQGrmB5mq+3Y8BhQcXFfn
            /aXpVWA50/ele6GaP1Ebr2akYbBzoep4k900D3Z1Zrimr/LyuxIRJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T13:40:45Z"
    mac: ENC[AES256_GCM,data:ZUnCFHqQy2xUsNOARlE7hZrxuXPQkstt4RXJlS+00xTlymGTxiPD+OIM5MTOYqlUkQUKzLxWgEsfXXJggmE0m5OWK12Cq3zilzzmqRwGDqnFdwvNbRPiyhmq1YHRhyBEWdEJrxfBh24kmg41ul4idjeHqgVuuwwOfUvAWJ/ptEY=,iv:otjs7SMvVApWFKVkzFEXBtmZdcxTzh+NiFuIlr6S0uQ=,tag:v6PomXBGULpCN3l3kExQiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
