#ENC[AES256_GCM,data:O0Gw4Y0ik4L8IkFoCzHTjPnmozw1vyAOzGgO0sMMeO2jE1RYqy49JMqizH3H3Sx1HobTpSc=,iv:j2ai2C82c0+uH4nBFsy9xlsiO7n+wezedvMIYgycgbA=,tag:2DSs8+OID1rG3W2IYnJ4Ew==,type:comment]
#ENC[AES256_GCM,data:5CJiFngvJOIz3G102Vv6onzA+Qbj0LnoQdW387zWA76andZESzr4OMS9gx27MQVMWso6kqHaGzFgR8iOE3CN/Wsj,iv:tCA5MzrP/JeeKasebh4k4uNFxwf82kyICiJpCRxLkJo=,tag:Oh4AYDKFdSHc/Q9C5mjKxA==,type:comment]
#
#ENC[AES256_GCM,data:Udj6rfEAmgNS8drcHOzZDfr8V21LQqhG1wi8Yias2PivcO+G1llqsdLSXxEj3NgOtHwedF/vbDpZVPXE1jBU,iv:QDzNMcL3mH/dtJIWAeb8fFsR2nBDnbaQp7ecVfEZwgA=,tag:ruUIEnl0XH776GwKfxXNcQ==,type:comment]
#ENC[AES256_GCM,data:k/9QmsbY/s7+5WHFfk3bacokhcerW+0eQHcvTi8LPl3MdHuhRe69Z8DB,iv:/PrXZ5jWU17HFzXrrfRmXm4nMNbIK6KSMsWqBVL0JtE=,tag:yu4DAfi48wQ9V+beuHOMiQ==,type:comment]
#ENC[AES256_GCM,data:BYXh8GqYxPe9E3qAnamIW8dpNni6gHaAZ3ODpLrcf0OdBdmBckHnR019RVW43iuRvxPNvw==,iv:TNFj1MjEGroUleTJuKQseHo+Q1O8FtLDfiN38AWuGjs=,tag:gMO8+5NFiY+Cpmy6e05N9A==,type:comment]
#ENC[AES256_GCM,data:dcGIKszc7BESLGtqJKlsB8JgIiQZlt4aUBStEX5NBpRxkiSkc4ZwparK1BI94nqxn58YuGrfue6QF+iX/Q==,iv:agfshTrnpjl5aumaUTf5syxVJ1n+9EwkoBPvO9Q9I+c=,tag:Fl1v3UtU8sEyGBVfmrBNlQ==,type:comment]
zurg: ENC[AES256_GCM,data:DBI=,iv:qKace4jUIGikNxdsnkM150X5yrQG0eutgCR80u6t83g=,tag:pXNDxKkt38I21Q/z0EAcIg==,type:str]
#ENC[AES256_GCM,data:B7LAeMQX/mVjgYVnyJbw8eoqh0/6vg==,iv:tQpMix6fu5vNd+HVg5lZH5ppIlEe3T8Y0xNMcUMogbo=,tag:gIvX3tvqHA3NfSh0/eRZ1A==,type:comment]
#ENC[AES256_GCM,data:VOFnxvg7pkVjbFtToZBqmyKTGLmjC+7WbFBBmcewJZ35FBVmtJ7ohMAOnZg51HTqag==,iv:xmfvZyHEISOPSu6Aq/0yA3vVQ1nVkGGbcveebDH+2qk=,tag:YblQKFM0nqpwkNMWmYj57w==,type:comment]
token: ENC[AES256_GCM,data:zdzwag7dlx+9rLv1aJXHwAzAe9vOrelvPTHEgWu38UNg0uy1EzEf11byuVBAGMNL1mVZuw==,iv:8hBDmdw0FuStfCmI0O0arHNxGDOxfKshNtyFUjaGvKg=,tag:HZIZsCaEMdviE11x0OLpvA==,type:str]
#ENC[AES256_GCM,data:rts1fU5jll1xijL408iYM3UP1cufwaC7nZzDTQ==,iv:oqjmBy7UyONEoQHWkews5hobydpFGuFSud/Zhtss6ts=,tag:hqkBwHv4Q/Su7yU5xk3Nxg==,type:comment]
host: ENC[AES256_GCM,data:8kArx3MF9Q==,iv:W1PFwhBoICLsoC7UqbnY9Gqwa/ydGFC0je98SxXwfHc=,tag:iU2lFYkluuzWvXQp/kSuMA==,type:str]
port: ENC[AES256_GCM,data:5B9Fqg==,iv:e4ErcYlmgq7OQmR5ozvpE8dHYyIUviayihX1nZ60+ZM=,tag:AElJzBDGcKG+3dpR9eaO+w==,type:int]
#ENC[AES256_GCM,data:70V0Wvvc65VGwbe4ugBs9vtRPmIoFyEOcnx2OzzA/bSD,iv:frR6sjIglUwwUmXRzL7XrOcU9yuq3up54F9TCzJjeeI=,tag:GugQCjCcJt+VXqsvx4jIRg==,type:comment]
check_for_changes_every_secs: ENC[AES256_GCM,data:Jpg=,iv:TXKKw3/hYySMQxjbifqENgffc26SUc5qnf3mbSbaj1Y=,tag:DOcZiG+kVBULDVX4IB7zmA==,type:int]
#ENC[AES256_GCM,data:9li3ASclyCPgPZxpthdkdSJ5C4A4P3Ma,iv:6/BGfjl5x5BqQNK485vfV0pzRL0xlvUcHSZX1Lk/Lfw=,tag:puKZoehvhKNSuyVqzf8QAQ==,type:comment]
enable_repair: ENC[AES256_GCM,data:g59a6g==,iv:dCIb7LK1zoCBAkIqB6K4potjIhsgls5RlzKaRbqaeVQ=,tag:w/7rGokEzpDvEtuE8jZT9w==,type:bool]
auto_delete_rar_torrents: ENC[AES256_GCM,data:qj+Hmw==,iv:kRUasB88QujFqekJ6SuXX/Ejr0SEJ3g5CKFGtJQkXJ8=,tag:xfMCNtyOpRlSSflk49lQVw==,type:bool]
#ENC[AES256_GCM,data:iTkjsEIHbXCveEngJwuMDb/yraSnXWA09EqK2WgsVIMHeY7n0MsxNwpQDoybuHnW73g=,iv:xt9YQ2zWniQ5IKT9Ht9/CZ68kZyAL5Sqtk5cL4yg7pk=,tag:bA89VpDlLLCYdiaETUB0aQ==,type:comment]
network_buffer_size: ENC[AES256_GCM,data:O4QFnujJ,iv:CXAsr2zTGbjEVGrf1byWwQ9bHFH1CBCHyuHANrGteXc=,tag:K6yHe9pA5hl2LRiQWxBaUA==,type:int]
#ENC[AES256_GCM,data:NW5j6y4W3HECBD7g3wnEqG9pvEkK82lvj1rvk5fBY3f3gWzRWOTSTZefOiQv7SuMdS0DGndJyj4824dU,iv:EIpQOVoOsHxuH8JYy6LLEjhLZcOyizJuph8HTBMZoXI=,tag:SgIuwbO/0r5A1VetnJ16iw==,type:comment]
on_library_update: ENC[AES256_GCM,data:NDQb7Zk2HmuRQBOlCyC3CEZo8Jz4RTdCkpFzCydFX6/4UZAVrV7/kF2mA9S+31Rjor7laIw=,iv:cZHWTIOWW8fDwm8R/fmb6ZNJ20xAiQd/Lu5YLk85gVs=,tag:JMsJObxpDLFE3f+VZu2sbw==,type:str]
#ENC[AES256_GCM,data:u83KDzDJ2BXV9RI+cKqfXNUlng3+ngY=,iv:RiI2j1mAiUP1jVXeITxgVyr8CVO7uoUDiM0B//q9MCU=,tag:vnw6i/rxZMwWz52xKRkdTw==,type:comment]
directories:
    shows:
        group: ENC[AES256_GCM,data:GigaG1s=,iv:p6LR38JofTw6U8IVyB7PC8Qkg+d0His/EvUQcOD/K6I=,tag:L7q2IltCdHxtcgdIWxuiAw==,type:str]
        group_order: ENC[AES256_GCM,data:iS0=,iv:g1ow5HZSFl4xZK3LA5y0YcDejNZBYgBmH34qezw0TxQ=,tag:iHGdQmlJhsbGDSWbAFmQyw==,type:int]
        filters:
            - has_episodes: ENC[AES256_GCM,data:cAd9fA==,iv:nLib+D3Nwh80v/sPgrJh5PcmuXGnOx9qm2KSAMdGWMg=,tag:vwximS411Na06X1JZht8ig==,type:bool]
    movies:
        group: ENC[AES256_GCM,data:P7q3DyY=,iv:PCsfzXga1HM3H+b0cHxzDo0+mFpvChu2zxyuJDaDydk=,tag:xZsK4NWT0RZ75DYlPAvYyg==,type:str]
        group_order: ENC[AES256_GCM,data:rCo=,iv:KuomCj/r43dPNApyDDQzkFpw6EA6X9k1+MX6ND9Jtao=,tag:w4NvliqgotuhJbeXKH9tvA==,type:int]
        only_show_the_biggest_file: ENC[AES256_GCM,data:eRSrJA==,iv:r2xCk3GAQWRQkzzBkvINyHOYkCLGonKjsWAJMcnWkoc=,tag:P4z1kGRV47LQaQbrRIbfXg==,type:bool]
        filters:
            - regex: ENC[AES256_GCM,data:BipEIQ==,iv:BCy5k5RXKYQ11C3sdONxr+A9ODG9u1YwmY+eSU6jXeY=,tag:H8Ft0uDZ2DfooabNeACW0A==,type:str]
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Sk1VclVFOUs2NXlacnI4
            aFkzNytpOG0xOUJRR2dmRm9YZW1ubFN5RjNNCjg0SHlrUDZJbVN6WWZDMTI3Y3lo
            emlyRFFDVzFUSDU0Vk4rZkdOV2gvb1UKLS0tIC8xQVNNUm5VMG54ejBNbXMvSGxq
            TnRsZWpYNVdvK3Fxc3l5TlRoNndmNEEKZnSvYWfDZHeVcW1bTcvokandi51xvVOp
            2khSQWBvWSpr7zv/vz2LLIzrVeWqt4jnOFgog4I2MM9OXCLsUbwSXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T08:52:38Z"
    mac: ENC[AES256_GCM,data:+qtFXULCLSX08zA/4HwpWJvYaHR5dIjjSwQW4owz1K+quv58zjLBrelVqoxwoM5I5otUxdiXwAY1ZfrO4YjEEs3AlhRXDWzO+3ngfo0Gf3wqTBuOq2lzqJ5zqrQiinP7BtHwtLJwrRwJ+2ufsjGIuxhKh/QDhhDELeCPG+rWIgg=,iv:iCCwwpOb2B3bhf1aCeejg+eLLFx0GqIG+wTJAOCqgdI=,tag:EPyAeM8YdfyRbN+08Po6NA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
