alerting:
    discord:
        webhook-url: ENC[AES256_GCM,data:cCVejA9kad7IdvERigB4c3zmo7+6nR2Vo+RIqvmp8p/SaH2Gw/oLyBsX36thqrW+LYRZR7lMe27RBWvWOm36Pe0pnUBZExeK/VHSRjK4sHP5OzT0G9S9oJXQ5MKe+XexMI+LvdbFj3Td/Gp3S05Z6a/H26WMUDzS,iv:/zXi8zz7FDERtjyFEezwp/HI7k5Cm0BC9cLFJlFX3xA=,tag:qZ7KU/mopg8+NxMbkBSmrA==,type:str]
        title: ENC[AES256_GCM,data:TuHkfs4XM2cK7J2J,iv:Iq8/DnB70Oe8bFEoQwtyO2P1VosCPbSVH0lofs3t4XM=,tag:ymGrHWyt7KXmeKRhybY6Xg==,type:str]
        message-content: ENC[AES256_GCM,data:gV/y50zUtQ4JV6BtNzLmpC+LXUZB,iv:szqz1WSj6sH+6m2rM253GcET9rIFhSchjuFJsoLow7M=,tag:sm8PVjwCaHBonMS6TOrzew==,type:str]
web:
    port: ENC[AES256_GCM,data:cDWW8w==,iv:8CME4U1UvtYW/BZOxqamKnlj+ibYww9O3c6MtIAcL+o=,tag:2ZmQ2zeMfZ5HSrTICKsxoQ==,type:int]
endpoints:
    - ENC[AES256_GCM,data:kJVgWuGdICdJdf4b6x+Rb81icZOjuRo=,iv:39uq0iagJRQo8W1H43GYYoEhtsRlVcSpETqwmFwQKLg=,tag:hL3wj5f10XZ+pcPtlgSXAg==,type:comment]
    - name: ENC[AES256_GCM,data:bb6QKA==,iv:l/U4r1mK3qSpCtRiWEve8uapORY9L4gTtgB21fiO4K4=,tag:B3DsBSpkB654gfpc0FGx6w==,type:str]
      group: ENC[AES256_GCM,data:ZDGV2CI=,iv:se/nI6g86rTb84bxg2f3TZ7rNZCoIE4tRg5+5D0pDYA=,tag:SV1NQpI0E4C1z5K4ZKy9ZA==,type:str]
      url: ENC[AES256_GCM,data:D7sdlV3YDSg9eWq9fJAuHHA73fel,iv:i2avA/qL8jpaN0JCbKFbtbnFXdJeVLwJ0GXIWMFhONM=,tag:Kl+3TahgcCjkjkl7oz/iFA==,type:str]
      interval: ENC[AES256_GCM,data:Hlqy,iv:dg4XzlPOSQGdL8vdswZelMVBcoRppUVzRFAFuQmvAZc=,tag:PYn0ZXZCnfOFYOZf4TNMgw==,type:str]
      conditions:
        - ENC[AES256_GCM,data:0hCBk2y2Tzx7vV+MlsCs,iv:KKL5OaGj2L+wjR/ckP9iwdK/ynAc+aFuhNJ/Ylqw3sA=,tag:LePmK2aguuytvpSeGyVB9A==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:1n2fZAk3lQ==,iv:Q6x7Y61rXHjeW2+uo9u9Vs6S1xh4ihK6qcVGDqS4uQ4=,tag:guIcILeiewYRyvKzC1I+Dw==,type:str]
          enabled: ENC[AES256_GCM,data:Yj8crA==,iv:X8UnHT2LwxI34eg4T4GnKer0q8MLdl+HOiyEgVuhXYo=,tag:sTljLlRGrL79aikiam4PhA==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:TVJjqA==,iv:Php4sLgRAGw+SGBpw6z+yGXPuzeAguEu7Flc8W15ua0=,tag:ACv852y7S1zPEk4RetpDLA==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:9A==,iv:9rQnnRiV1EU615ar53n+ZGUY4IJbQyCaKIruiZVZros=,tag:7MzzmuwDAgPi3Lx0y1wjPQ==,type:int]
    - name: ENC[AES256_GCM,data:JyiE1g==,iv:yLHMUBo4qxxJqcqphva0hVTtQHcCjeBhoBjRxkHkyCM=,tag:rObGFnQYeFXLSLEbaD04yA==,type:str]
      group: ENC[AES256_GCM,data:sUzw+VQ=,iv:lx7vs4N3Y7boSWrvmTfsuVSB2vNvAqMlYeTyQM+Z9Y0=,tag:wHoNWikcu9xmbtBzf7QXfg==,type:str]
      url: ENC[AES256_GCM,data:vJUNe7IvY72dqiKGx6emm5DTksMw,iv:TDiwphZleZahXyfBaT7ytx6Rw9MkyHGAv7/KgkgKjRo=,tag:QTZJFQmNtpgup9m6lxZcZA==,type:str]
      interval: ENC[AES256_GCM,data:I6EX,iv:j/GqWkiXC9QZum333gvAdgFD8KGKhuV7AaM5O0KSXUU=,tag:58XK2lBr7+HTIojtoM1EfA==,type:str]
      conditions:
        - ENC[AES256_GCM,data:0Dtsa6/eBBA5jY//xlpV,iv:mXe8rv54TQFjwANYOYvGMsRAfi3j3obfzK/xciUsRx8=,tag:g5HSYrfOw8902gc77sv5+g==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:/VQE0nbTLA==,iv:Z1Ov5QaNHS4zcMcxvi13mEIhcYVgaVNwHf84ox0C6Ho=,tag:plg4F+DyS3okJ+XIw0xIMA==,type:str]
          enabled: ENC[AES256_GCM,data:2Y+3Qw==,iv:RF6zJxiJf7SObVMC98dor0LKNNG/bmeuMCuFWsAvaSM=,tag:/cR8RSsojUrP6/4BPESlTg==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:h/x7Dw==,iv:ukT01BKxHg4lulVQF9VfX1RnGT2rRE1MGCMoDSmG+Sc=,tag:Z+sb0jVrSrKw4cJSUcrWAg==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:Aw==,iv:iOW4zv08eR9TjRQ1L/A1UbvRxOocwSWerdl+AHp2KMg=,tag:o0W/nq31uWLd1U5UpZ5WxA==,type:int]
    - name: ENC[AES256_GCM,data:uZXfcD2m474=,iv:+rcJGBZYngIyAbEeoPkYxocUD6RLe5tV7fbESQ10B10=,tag:Ayi6WqeNVG4TU8OHz1wYBw==,type:str]
      group: ENC[AES256_GCM,data:aQYO6DA=,iv:sMycPHbd5I3CDVSw011dKeJIhymKQ3hv0yGAdqRCFFE=,tag:+Go8sgQ7AEefagBsFMm1hg==,type:str]
      url: ENC[AES256_GCM,data:ssx0/mFiZalHjNAVsFPGIF84GOfc,iv:OJAZOksdNqy9SMMFNDb9ycgS2QbQdN99x2ifThqQ2O4=,tag:sEZ9lsmM97Zl3XEGo/CjkQ==,type:str]
      interval: ENC[AES256_GCM,data:Le4f,iv:mVlN/ALBTmaiXXSgZveu0APoFI1BDGpY36w28cHTiRA=,tag:3HjUidQuHg+ntPJK4j8U+A==,type:str]
      conditions:
        - ENC[AES256_GCM,data:gmzk6LS0tl0ZC++X3beY,iv:yIXT14Q4kZpcAzoW2Bt0A76LP7JcpJbGSsX9j6Bta8M=,tag:Qhh7HI3WWsm43FdB+T67+Q==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:GBeLLWQw/A==,iv:1KtQ3NzCVd7vn0Q091DknWq68yH/XqhNZhWjbdMR1Us=,tag:Yma/mZKOzl1lHVhCf9Gf1w==,type:str]
          enabled: ENC[AES256_GCM,data:iSjupA==,iv:pQ8k8bCINm33ao4CKS1EaTtvT1FwcT20nUWMwEb0xCA=,tag:XTrhVF+MEYHPHOmm2bhetg==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:fj1IlQ==,iv:2DSzdIk8sHPDElI2Hogy+3k1OJSEoEcDzyBpwygh/BU=,tag:vlrHMkk79OU75JsF6JEPVg==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:iQ==,iv:eH3TIft7RsCA7QHvcpWBAR1XtLIICvTUDg6dVhJDQBE=,tag:uILjUp3wjia9enSngA2qBw==,type:int]
    - ENC[AES256_GCM,data:wKkfanLhTd428Gl6cw==,iv:SkG/SKn/c/CtGVbP9YXfuLKfzABy5q+22ExTNpwcsIM=,tag:wSHjl+re1akF0jTuHa+Bhw==,type:comment]
    - name: ENC[AES256_GCM,data:6bIHDWh0Oig=,iv:+JJI61VsF838GlpVgeKEvtEKfJrPC3seQKGE392c+H4=,tag:rFStp1GzimwUcIoSOe8Vdw==,type:str]
      group: ENC[AES256_GCM,data:22E4tg==,iv:Yug3yAWkcQwQkNNiiTzvjzpsaZ4mPkvUOFdthW0/gFQ=,tag:meopfYjdlJGhyjja7NGptQ==,type:str]
      url: ENC[AES256_GCM,data:C/ELAZsmWM1G2aU65Iig,iv:o7A1AodTjaxgGt9ueY76P/+MV0wrv3gukl8JNUf7bPk=,tag:FBBoO8gNA1kTqBQgqznapA==,type:str]
      interval: ENC[AES256_GCM,data:TgHu,iv:0OgcrfngX49YHhLgjuflYKbTKjPmqk1htraOXTO523A=,tag:0rC0knV/3gcJ8YYc0DLTWg==,type:str]
      conditions:
        - ENC[AES256_GCM,data:qwocer3TNKJHnkOpjO/s,iv:HD4+4vDbSMrym3e65oYt8tQF1RWrgSQLq+utYdwTBdM=,tag:vkS5W2a9tGUhqFCOeqxReQ==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:Vsoh12BrXA==,iv:3m0ywd+KGos47fitpTnsR0It2qMwXxG6iZlGrFQ3Wqc=,tag:G167UKm6yIHygQ7vHx0u6w==,type:str]
          enabled: ENC[AES256_GCM,data:bl40Vw==,iv:NnFgrwOZOkjJufm0CWtMAcXGlg6ResUPWAzyZhNtoTE=,tag:7MuH2KEjBE25THvGutw9Sg==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:IZHDUQ==,iv:oQ16m+aJyYZVx9SG5yk5tkwpzQ/Fgi7INCahcWWok24=,tag:pXX4ZjwF1OaRUIbfG+KUhw==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:mA==,iv:aIqid7p9SoNb2CA77xdsDha1Ct2CadTZ/WE3Wev2O7A=,tag:wgn9ymQd31Nj4SEydwMVkA==,type:int]
    - name: ENC[AES256_GCM,data:lo944QxongEg,iv:gbcnWwtxD3Rl2EQE1A1h1QiFvfgDkU9im3o23go+4S8=,tag:I+dmlKmumbqnLo+OdNEjNA==,type:str]
      group: ENC[AES256_GCM,data:BpDyqA==,iv:HSmFzmoWD+HxB8uE040E5QwUJp7XScOWU6/g0t+hwfw=,tag:4hWq7Dmmo14IeFju+oNq7Q==,type:str]
      url: ENC[AES256_GCM,data:IO+/eogSHY7omHLwLuysGc0XdpPIVQ==,iv:EvShk73Zl3wSd7irMH9rhhOTOywByewc0oyXLHkYrc4=,tag:OsZGgEwUA4YY2BW4nc6VyQ==,type:str]
      interval: ENC[AES256_GCM,data:qc9S,iv:IB0X1NK4TNZIl+/YBHxpXHQhgG/83ZrbY+/wgzUe6+U=,tag:auUWZjT/0CGwUNGz6+JKkA==,type:str]
      conditions:
        - ENC[AES256_GCM,data:U1AbbaXmqq/EHlVJTiAE/zShcQ==,iv:LcZDjCqIzxxJu5M7WelKY99XfoDl0pS4eXZgeWSH5DI=,tag:Y5wOcYHlKW+UqDNs+O0XtA==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:+MI9Unwnyg==,iv:zZmEFw59U0ac2KTGN0FuC/nu6JrYHConts708gEgA1I=,tag:53pRGv7KJI5wJ4s5P11S7w==,type:str]
          enabled: ENC[AES256_GCM,data:u45wxg==,iv:1b8TWl9roJYn+vprpS890cnoli3grWFyZ4Su356cxM4=,tag:OpJFvmsdFNW5dnmnwlvrxQ==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:znsT+w==,iv:U0+vRoDW5sCm2lgiiV52ej/gLs9g7c/swRoIUpfqAx4=,tag:S5nvY1dO8Pcr2oLbv10a3g==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:XA==,iv:m0mr9EaYwS5HablYOd2PFt6FaNVcpKn0042bBwnxWbA=,tag:xyNCGz8IQUwzrXs8iVuVew==,type:int]
    - ENC[AES256_GCM,data:hXSmNGxOE9vcOYHymNek8Y3PxA==,iv:g23otmpom4bcaRcma0XHo3Mr11RjBPKNggWEHwLP2YU=,tag:POjtKDZ4kPp79+yRY9n/Sw==,type:comment]
    - name: ENC[AES256_GCM,data:iT3yjI2tDg==,iv:VAn0zz+FOJjyN53Jjd5wTTLMGI6tXuenDoCGKsCXL3E=,tag:Kaf/CUfKZ/Z0RNloTUX84A==,type:str]
      group: ENC[AES256_GCM,data:UYgsglIglIaYvw==,iv:mABjEg4ZRCPnrnWiF+L7Ainwf2uNzSb3gPmnHnjep3o=,tag:erui4EVdFER4AiiATDoYfQ==,type:str]
      url: ENC[AES256_GCM,data:JCl707AxrMjao8wT/Bnt2CC1vDuZh/F05O7DoflbJ5c=,iv:4GBJni3NF+VfCM54WPw/TfGW7f2Qvs6fBer6wDwPfgU=,tag:WhCind13NLA1WxR7vUxR+Q==,type:str]
      interval: ENC[AES256_GCM,data:2Z2I,iv:eqvHcIWimakDM4J9dL4OjpvbLbKaSMwbvMFGapjAXSU=,tag:IbENTF0sddTURTAbvRA1og==,type:str]
      conditions:
        - ENC[AES256_GCM,data:pxQhVBlCqMgsaqhF5rxm,iv:aSSnTYJ99N32QvjN7bruyl0HmJyE3OXafFB7g6fm3dM=,tag:J0Gt1d9zIIs6JQca5EChBA==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:XZMSUPUawA==,iv:1M6tsyXLb4jmW8Aa5UFORurMi/M7lgRdoW7Ai1ss7Yk=,tag:vMsrtYAofWm3dWkc9kXK6g==,type:str]
          enabled: ENC[AES256_GCM,data:n9cwRw==,iv:Wp5jP6fQJY3Bpw6U5kEb0UOkFiWxYCh5+j+HkClVUk8=,tag:si8yYjUN6SGTL5UY+w7n+A==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:Zrm0fQ==,iv:kOP7Q6Wj63hEnxaBW4gGaYlXft3MEVpS9D1pGW0aTuM=,tag:KPrf1HdcCxAQs2ZilMuGTA==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:8w==,iv:n/XjMw2C2WF0+EpOvY8MHK/f995nucriCYYkpTqpoKM=,tag:zTFWLTUae7rhICJ9njH+DQ==,type:int]
    - name: ENC[AES256_GCM,data:R+4f9xHzFWQ=,iv:oHLJfFbJf8aQmO/EZ0L1gxs9cxb+ZHUxSv7yq6BNzUk=,tag:6qV7oP0lz2267wUF/Cco6Q==,type:str]
      group: ENC[AES256_GCM,data:MUe1bjUB,iv:bYgTtaSbHv3FByl9RvuvAQ7Who+liCFzEtDTnSt003s=,tag:3N01gOWE2+9K/ySxXRLF3w==,type:str]
      url: ENC[AES256_GCM,data:NmgK46C4vKAaDG09+8tTl/ftuGENV8A=,iv:ozGUqEubcKHpOTnkBjkMAPj7P7Yp0DNVqt7E+zXe/XM=,tag:b14VOR2RFEr0ks4aDMZqBw==,type:str]
      client:
        insecure: ENC[AES256_GCM,data:wgi1GQ==,iv:gZ8L03v16X/qhIS4FWH71ghwClDVYsEGPuLO2dwdsZs=,tag:84/pkvF+BN7yXS/uexZF7w==,type:bool]
      interval: ENC[AES256_GCM,data:Ods/,iv:3y8JD9nYoxtyubhQtWUruI2IQnAEeUg8pHKcJa+BhG8=,tag:LgYo9HFfqzWyQLxI1qtHlQ==,type:str]
      conditions:
        - ENC[AES256_GCM,data:Yy+Z6QEg87pkPRqMJnIBTET6gGtnYtJH6Q==,iv:Nb3V703oLXm1UucBsXFw8oOiFiNCRqVsrvGMtV+x+yA=,tag:GKnEBwuLiGeLNgwqPN8J+w==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:YNFyXt6uzw==,iv:8y9U7qNSFgbUpn7esLU8aNFvWiBnc8DzjoSg4qRV8Ck=,tag:gprTYO/sTtgrRYTWex3P8w==,type:str]
          enabled: ENC[AES256_GCM,data:Audgfg==,iv:ULsuobhIyyGUqvCWI8dLN5Vuoggg3WqAzYi8uymfvDc=,tag:00r2HirNdoMyXrjzYanScQ==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:xfIERg==,iv:XKeH1h6xgphMLPmexwaNv4bq1i4KkkhXmN+oPc1DgOY=,tag:tPMHFjvtjiSZdkE+5S64cA==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:Xg==,iv:sNFru34v7IhPAqKNYRqXuAWICIdOHcOu21AR2iFZUQM=,tag:y9PUTqE5qGffdDXnbkEppQ==,type:int]
    - name: ENC[AES256_GCM,data:QhTqbVfwvAbx,iv:EHYdm2doDjevEtfsi+6okpa2DP0yBpf9NJi2h3NIo1Q=,tag:zqNMgpbIJemDQgkVI1R9VQ==,type:str]
      group: ENC[AES256_GCM,data:lIIV1blt,iv:tgTgHYqgBnG/wZXxVEycqX1finwE8f2tg1ljz9S5lrM=,tag:aV22X0cpniMI41aCKf4T4g==,type:str]
      url: ENC[AES256_GCM,data:IC/G2gcCEr19pizC+9qSVCq5Ocg=,iv:5EmkqyRXa9dDdhBv96SaWGJZl6CN082Ana9htjCezB4=,tag:DOgNbCQCf6O6PcxCTwkr6w==,type:str]
      interval: ENC[AES256_GCM,data:EVIZ,iv:RZBBeHUQR5zZiPEAwvobcx/CBHoiBgY6F8FeSURqwZ8=,tag:8uS6VDP72ZirfbyrB3+Iyw==,type:str]
      conditions:
        - ENC[AES256_GCM,data:8I+H0rQp/u4M7kSbreLcceySkA==,iv:hquN9eVMd6MqQzAJoGeclUsQJnifYbfgzQCCDO/BoYs=,tag:9d8cHSQG75NDDanjZa94Ow==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:l6HTZ7bPOw==,iv:3dGMJgn2JAnrCLKsRG3N9FcpU/9yNJFgdWq2KL2AFNE=,tag:Nij5MKG0xA2wGnEwjf2OlA==,type:str]
          enabled: ENC[AES256_GCM,data:4eHhww==,iv:aRjAysi6zY8SnQ5uEvFWzWVajZiXCJjlxemfgKwKvwI=,tag:EebRyZwKIUFwfQit2EQiQA==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:WdYjXg==,iv:n60CiWicmlARxS3oUSCo5JUYIY++dukxnMcbQlfHGzA=,tag:8HedvxhEfWeKc07mag7b+g==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:9Q==,iv:XBflrJo51jKecdBP+WCX+uyOI77Vy4UN5DpnCTmqnco=,tag:BHaR602A4WTLj9yQBT0VjA==,type:int]
    - ENC[AES256_GCM,data:5FYACkXM+hO2Uzo5ng==,iv:PAdeO/Q/d+oUoCDUNfSGMDH9kuDqYtaFtDiuKNV3kOA=,tag:gxvDPfCFyGkTq3BCmw1/oQ==,type:comment]
    - name: ENC[AES256_GCM,data:9HSa6fBQvEA9zQ==,iv:1xeQ/Ay4dNYNjHut+8CqIa7mN043bF+54yrZwT9I6g0=,tag:M94HmzNdzLFpnUIOhCpMTg==,type:str]
      group: ENC[AES256_GCM,data:StjKHA==,iv:HSTLhdbW105suFEP6C9ERKFrjYRFeuUifBJ6OiSd6hs=,tag:ZSAhiOjjKmmy6r8kIRoPOw==,type:str]
      url: ENC[AES256_GCM,data:bQk44jMmMF8eRpONpGa4lwWj+w==,iv:vLNXmKGXb3tHnsff3p0lZcWICDjVzddseR5WWAEtDJE=,tag:4XhaG33JrzFjurkEtNrTtg==,type:str]
      interval: ENC[AES256_GCM,data:h/lG,iv:tS2a/jd9yAZlE9XzNIov7/2hf6RlD3Ea4lfaOgDeoOI=,tag:O12tko6ZTkdzqGDLagg6Eg==,type:str]
      conditions:
        - ENC[AES256_GCM,data:1fWUBHwAKaSKjtNT73L1lTk/WGn5D0v/qJ18KZhi,iv:jK7E8NXCAL9wnlrzZZGha2IHRH+Lruw38LculbV53IE=,tag:vPftsLBLTXVboZ69KofbXA==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:2pXn8Ywz7Q==,iv:n38dWJz/XjrXfB6vVNOigXc1ouJNVa6wexlIYc5Sc1I=,tag:XrRhc/IUKRRpkFADSkJJTw==,type:str]
          enabled: ENC[AES256_GCM,data:HlGmCA==,iv:gLrkaMoB7hrFO4tmnV+mRld/1bYzlbGtagQFS84W+pY=,tag:K5QU7C8caTNUkw9axWIoDA==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:HoJKcw==,iv:fsM0it7JzbmIt69EcZUWCbWcijFJHgcse8rZdQL1nuo=,tag:JxozwwXbHHqFAF4s2IudAw==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:cg==,iv:9+U0RqAucn6knioakKzXpdGKQta9m6smAGPptDCK9aA=,tag:df5Tp+wP59DaP23St7OEzw==,type:int]
    - ENC[AES256_GCM,data:O7S5QitI1QHddiw5f1qSmZ6u3YU=,iv:DW5r+KW2Q42XaAw+tUmzThmKt0Tg3iix/zbpmhKAhVY=,tag:XS7K5fP3hvLGnlUcIrxNIw==,type:comment]
    - name: ENC[AES256_GCM,data:hTVC+LnfndjS43YdvEEV,iv:xf6z6Axua1AYJz2CUHW/etPCWTlr66h1pnf5Rmg3tYA=,tag:V1FQ13BGlaiKbuEmaZp+LQ==,type:str]
      group: ENC[AES256_GCM,data:iXOMoPCWV370xGQ=,iv:8+2CiBVR9jXIuyOizz81jxHGhehHdJG/AqhWAcG0iEs=,tag:qDedCqiHckACayAOb1ru8w==,type:str]
      url: ENC[AES256_GCM,data:T1XU0TMbmGfqFbpKGsN4kYCi0jBJ5GuG2g==,iv:T9iYzQRFrRE6iemAU4GvDN3waQmatY5WSxH65Wq36wA=,tag:IPYuAqBIw1BXMoUQH2vzVg==,type:str]
      interval: ENC[AES256_GCM,data:/y1z,iv:eCMgIugb0o6OijRi0VT2MedZYEZTNBmLdQpCnomQqiU=,tag:xAj/EvZmFc6kQAIu/tLw5w==,type:str]
      conditions:
        - ENC[AES256_GCM,data:SmApElYegZxcmoWAozDT,iv:TVKxDX8/ENZehAeCBHRpMEzbGHPqPWIKwVnV3++dLVI=,tag:V6n8hGdzrs45D/vmkhGiZA==,type:str]
      alerts:
        - type: ENC[AES256_GCM,data:/yH0pNNHyQ==,iv:rIja230aQg1a6p43wAiq4p56MKPnWbDf58BbBwKXPg4=,tag:1qxytzRD4Xk/BPjLw3HfCQ==,type:str]
          enabled: ENC[AES256_GCM,data:k1bjMg==,iv:OUFLJ/e+MF8fSKZ8JDr/dfQiT6iNerUjMMYU0bMB5q4=,tag:hOPVTQ/2Tb8qyzzRcUXCZw==,type:bool]
          send-on-resolved: ENC[AES256_GCM,data:DnVbug==,iv:MjvFOSYY1aK05YMO9d4tm8D7nVI+OAUO694jdfIIkxo=,tag:2vSjgJC9KwENTIOVJytxTQ==,type:bool]
          failure-threshold: ENC[AES256_GCM,data:NQ==,iv:zdcrb4d8ocKOc7Wysr0uIRTjx6ABXonCWfwCQVldijs=,tag:0RKnXL5Prws7kUe1a5H5pw==,type:int]
ui:
    title: ENC[AES256_GCM,data:Gf1DIV64ChqA0Hu3bnk=,iv:sDa+Yso/GbmGwHI1XVFRRCLrf9W1MskZBWVyI4XAqK0=,tag:LmvRsiBjDXmzHMNzEcPLnQ==,type:str]
    header: ENC[AES256_GCM,data:9Erw3eMulHpBwtfNCE2F+Q==,iv:Y7nMzRSdOYvmSseuC+1CrsnR44vXTBGVGT+HLxo7SMs=,tag:hJdog0uNyzGNP3ZSx1NBLw==,type:str]
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWHVzYlhyNTNVaDhwVHRB
            YkMrRGdQRFpHSHAvSFpTRTlEL3BXYmRRS0ZZCkdabk85REhzMWl4ejJmRXNacktK
            VXZWOTlXNG5tbEdsMlcvZmRTT3B3SEEKLS0tIFRnK1Q5Yk5yNzBBOWkwZjVVZVBa
            YlRFMXZLT1htRkgyUSs4bFNXUFltRGMKhoAq5SB7RHjAi1yaJNELs1TtaBf/Ao2F
            8yXiKxbK9wjnYOP92hqIStJxXrxwPV6JPcT1jInbpslaHoL5vj5OfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T21:01:09Z"
    mac: ENC[AES256_GCM,data:C3F8+RNUGIpV62RpJzzIpzYbjeLzvmymAkGPP7fDEYtPTTCfqZwD0PsKKGBfysUHmIRb4hVkzm4sHUBd7rTHsTb9lFtBuM3u6uMncQgoiqI6S8+NQQEQzIe1BzcPXqRmADEjHkh4hlSLaxDTYErxRNj80papwe4PGOlVj087+uw=,iv:Vx935eYJUCq4LGwqxiIiRuLEJh/rg/bY4n2LB3kzbqI=,tag:kpUAS9QS21JjQ2suQkDn8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
