tunnel: ENC[AES256_GCM,data:rAvp3RRqFcZ0riHuF+iD/PxkbyQMGLoN7EgnrgNViPcqoRJG,iv:TOS9sYIR2XSHZwZQs0GERQbSBlbUeGA750Kn0VZp+sU=,tag:4tqxSMg3TAKDTEn4hcCqZA==,type:str]
credentials-file: ENC[AES256_GCM,data:wM9q1ZMmli3fDAfykUkU6TQh9Hier+oG+TcNLCVIXOHH0d9yonxg2SX7aJ1W2XcfUL4w9bHYBw/FzA==,iv:PzQ9tUY5OYg7jdrXRmHvvlnYe6FomZ+P3DCTqoqA44c=,tag:D5xLwaDyG8/RyUETbZecpA==,type:str]
ingress:
    - hostname: ENC[AES256_GCM,data:0HhMUobCqI/ZZ1qMUlH3,iv:A0ceUiGw1hlPysiptrl0/nhoCuE/NvCZ4t0HEs28pts=,tag:yRv5CK7iflPQsfvuxraM/A==,type:str]
      service: ENC[AES256_GCM,data:bKHp8Nbq8H27WBkoSMhM,iv:NmqKg8GYCUti5SQsFBhz2jKfxag0AHhv1Mn2Xyb1WhI=,tag:oEGfIBDj5k25W0ZCiOmeAw==,type:str]
    - service: ENC[AES256_GCM,data:mAodZZZC+/J1rnnzeo4n,iv:O5+W3VhCzwv+Ogl5fNUrq4e7crWgP1OPmn5z4Aj8sgU=,tag:YRGeYsjGV1CsDY3nkMrmQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMk84enE3UHdFUkZJQUh6
            QWh2bzNCbVhBWUZpcWFzOHJLdndEOE9TcG4wCmFrVVB6R1c4cFU1VFR3U1lkQVJa
            ZmpRODlTUEMyVFd1WnVSK2lGQnZwZkEKLS0tIFZXWkVmSk5QcWlmdUIzdGRJbGpk
            SFJKK1lMZ3BuVCt3clREdVdxclJ6dkEKcUwhkZjpbbht5Lx0u4B5XHzhgsD7eOAb
            ZQjaPtheyPWrQVjZZhgTrtjqmfNzuYkSVRDix2BnFLs+rJIRXbhFKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T23:38:05Z"
    mac: ENC[AES256_GCM,data:YMokqqn0Cu+HyKo3oS4AdN38EubYO2ByRl4xYM2XDJwlJ36fOtT4XocQmElaAnFdm9qOjrhsTAwe0TNU302QFEBa+zk7fvAd/+mYvHZ5Ma/Pp1CqQf772tB0zvvVKjFJkd3SDbLsFAqazx5KKE1fRcAHFsx3wY7LOhTVQe7fPJ4=,iv:WIv+NnFoolo0vjWk4Kbt6YO7Owjg4oS1xi8KYGTMGGw=,tag:6XPmXfJskfeRzp3x2PL+cA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
