tunnel: ENC[AES256_GCM,data:/3/G+bbLXO765XL204JTXaugFSd9DwN6aiazyq975S5Sdg2s,iv:0qI+Noc3LSaNXc2lg2N+Y42/VQzD3h+SsOXb7q/4Gos=,tag:qhHRwHVAO05dYyO+wrPLdw==,type:str]
credentials-file: ENC[AES256_GCM,data:QbOsNtoZPdiITze0nXY+YHR09oVXSFXb3EzO7DABgg9aGz4aUplcss7tth5U8UXJd8xKfX/DcK4nRA==,iv:mYROE1YMQVOIVjE8ca2nD9FTftXpyMo7cZDO1C00Vgg=,tag:2w+pyNNeRqIfVLbl42aYsA==,type:str]
ingress:
    - hostname: ENC[AES256_GCM,data:LURbi4NHO0Poerc7pI05,iv:vMyUY3QyBhS1awh8eba1Pz+twWdEnZ2Nx5ZxlxZ1klk=,tag:xTu2wyNPvTfP/dFwvjJxpA==,type:str]
      service: ENC[AES256_GCM,data:NImWA8zdpZ83XXh7ZO0v,iv:j0/hRlzLh3oc93gLdOckebrADrkrkTbETLHbufjcLrw=,tag:fEZuzXDYGs4E4KLD8XzVzw==,type:str]
    - service: ENC[AES256_GCM,data:tmHaLkAucG7Pyg6I1PMk,iv:xo0jZVNxr9oMcDdefIglrMf5yuqg5TyKGhVMg691pu8=,tag:v6G4UUSkmZ7/I5sRBGl7fg==,type:str]
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwb21xSmsxNUltWmh5MWVV
            RlB4cDNOU3JLVnlCRm9mQytnVWh4dWFZYlZFCmsyUW9DTGlIaktkTWxEd0RibVRv
            c0RDQkY5SGp4VFFLUjFIcm90RzFNelUKLS0tIEQrb2FaOW5ZVkpmRS96NWRXOUh4
            TjIyaHhqbzhZMFZ3aWt1d2dOaFkwd0UKweUoMiBMYCcQZS/7AUU8jDK7qszv13j5
            ee8MPkVA+wGNJTo8Bof25qA1Dqx4JtHW+LOQZdKEKR7lqi71cKBr0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T13:40:45Z"
    mac: ENC[AES256_GCM,data:Qfohfy10P4/kSf6le7qXedl8NqddgH9J1VhNxcIkXk+qnUUJ9noWC1wcng6LwBEXc3jAXdpZH7xcR+H1ZO7Az+IoXX+KHW28vdTkPmKSFcnsIvfNjPQZZ7JbJv7Gtj2QeJDFO7QKxgE1HG6xbC1IdXCRZIFvN0fi6pJ4d6CRTYw=,iv:pwMb6k2P7Zu/ILPLDHdI0ubbtd1fE/uGex5d231wUd4=,tag:9o8zWzTO4Q4RjardtY5/eg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
