tunnel: ENC[AES256_GCM,data:LEesyY3Mw6sfHcuDhD1ks9f/wn/nfRFilb7H98pPAduva9Zk,iv:siN3tXgaETk7XTlw3wZWxYmdn1wgUXESz6KlrKnUMeg=,tag:faU1EdXgT0NaYcxigp1aow==,type:str]
credentials-file: ENC[AES256_GCM,data:yTi9tUjDxZaQLMabAsoq1YGEVXkaexNFMI1grYOUwbyImfvRBPGViUIwz0XpQrU7LPIF+XUFIIcKUg==,iv:+AfqZx5KBoW5LOzgRn+eqCEOl51s9U8wxE6NAlxidt8=,tag:zBIwVxnqnddRILGmadam/g==,type:str]
ingress:
    - hostname: ENC[AES256_GCM,data:vJ6HJlnmywwUXFpKXf/a,iv:2msxm/Yqg8/ZD4LLqInM2iAYCV1flEAJppujsK0lj+M=,tag:vsR2qD7VB1D0I3AEtbpqYg==,type:str]
      service: ENC[AES256_GCM,data:vtCFTWGugcnsUGmouCPp,iv:whcaX1CEHvCuxTh2yxBx4vlRLU3MVXNY9pi4JNZowVs=,tag:Pj6pKjuWMvYiymOQ2VvKsg==,type:str]
    - service: ENC[AES256_GCM,data:jf+4MfskbP7jrEcAjApm,iv:Na34iwLHMv2kdo+A8GVj3lZ8zl/maQHsUXNRTunV9qE=,tag:x4HzmzmeYkFqu23JvYmoKg==,type:str]
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcVJTU1RNdUZNUk9FQ2lu
            ZjdNckFGekk5eWlLb2JxVFhFdnFteldBZm1nCnpzTjhCTGdvUW1jb25TN2JVSUlz
            RndWdDhOdTY1NFFaa0dYeUx5bVBsNlUKLS0tIG1DTkxEd01CcWZJVDE2TFdQdUxo
            MFhONk51UU5Xa2VLOXdKZlU1MzA5MncKdRoIEVKFD9QvU31avEa+92srr+DuOHS1
            ZX47LKGKHKbjA7J+QLUYQMh1F8QpSDMOriDsMLQiebyW0jPtLy5QEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T08:52:37Z"
    mac: ENC[AES256_GCM,data:KFXdjSEe8ksb1gDhFm5/ZALx5IiaQfxrgb7TyXgWqjtxhWPrlNJ1kQgc1WOI066IY29J/0Wp83ibmITJxLilJ3S0RooiqgJ7nLDV54/dLsGfd/dxLnSymS9mBCAnxo6eBTJIqDiqFCpOg2uXjVQJyDfonjk/nVPtCVzVNTglff4=,iv:u4ul0ElE6ELKAWvQAerl/BIMQkZeNu7JC82qcRtfzHI=,tag:AsFA85BbW2/a/RZ0jNtqlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
