services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "9080:80"
    volumes:
      - ./data:/var/www/html
      - ./custom_apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./themes:/var/www/html/themes
    environment:
      - TZ=Europe/Dublin
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=REDACTED_NC_PASS
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_TRUSTED_DOMAINS=noc-local localhost
      - OVERWRITEPROTOCOL=http
      - OVERWRITEHOST=noc-local:9080
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - nextcloud-network

  nextcloud-db:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - TZ=Europe/Dublin
      - MYSQL_ROOT_PASSWORD=REDACTED_NC_ROOT_PASS
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=REDACTED_NC_PASS
    networks:
      - nextcloud-network

  nextcloud-redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - nextcloud-network

networks:
  nextcloud-network:
    driver: bridge
