keys:
    b2a302a1ed06: ENC[AES256_GCM,data:qVI+H1NgOlTgfKPAi60L7V53DenmlBsFbbEeydIe4rHPx6+gFC0dyQ9dtIR3eBUnJsM=,iv:YIvkz8V267KHgGUWnTZToUa827EF4Z8GhLA7TuQWrgk=,tag:PGLN1SbjBswQvoV7dD0LsQ==,type:str]
log_level: ENC[AES256_GCM,data:PcMXMg==,iv:FnVYZjH5BM3OQLagfd5xASs+1sNVTDeXTNJJOCBkCGo=,tag:vaCH79gVvDarpmIsJ+IFCw==,type:str]
rtc:
    use_external_ip: ENC[AES256_GCM,data:UAtL6A==,iv:EdTH8LcrB3jZBBcjJRSnWtCjkmXIXQbXrnqilYH/rKk=,tag:xLjDoGC29nRZKXIGlej3Lw==,type:bool]
    port_range_start: ENC[AES256_GCM,data:NN2X2rU=,iv:eT90TsmuFZjvyRgrS3e00BwunB4lTL2yv1ZkeTPeiMQ=,tag:3iORqo87prSg8J3bQ6BZlA==,type:int]
    port_range_end: ENC[AES256_GCM,data:i20jANE=,iv:bjAu0UmHAXbB4qHUNwOXFYgiyKccqwKyMRB8IKnPA6o=,tag:17qlpjJMB3hed/hvXplgjA==,type:int]
    tcp_port: ENC[AES256_GCM,data:+P9B9A==,iv:BRc/i+eiA05LS5kwe4slX4Unt02VhzDvS7kDlKRxMMQ=,tag:JDJAxG/06kDBCYvXPvbgBQ==,type:int]
redis:
    address: ENC[AES256_GCM,data:UEpssyH+mUS8wg==,iv:jmDFA9k6glnJ4war7mcapGeL4qhdd2dHu17Uz1b46Lo=,tag:b/c84iWsvfBgpvmsqAGS1w==,type:str]
    password: ENC[AES256_GCM,data:PvqqC54=,iv:uDd/B4r1bq71OAnhGlZ7eCuuPGxmuUFFM7ZxS3QWwGw=,tag:c0oZ+ze15eGHd03tMDdzuA==,type:str]
turn:
    enabled: ENC[AES256_GCM,data:aPVvPb0=,iv:D+Pxdekf+jhGG3mVbIHxf7wKJ+zBAQ8J8Kp4ZidG6EM=,tag:j83dGpjE5Gk3Uxw0+rKSrA==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab2J1N0pZc1JreUhab0Qx
            RTVLVVhZZ3Fuei96d1NvcUQyd0txM1JTVERVCkZpZVc4RE5UWk9iQXhaaWlPVitv
            dXMwUWZ0ZXpMVWhBUmFTNGYveHJGMWMKLS0tIDE3QjhsaVQvTTVQMmNCWjFvZnNx
            Wjd4YVpHNkJ3aVFRcForWnFFN0hycEkKzf4mDmpsoz3d03hruw6GAzQggT5z5GPH
            gv3kY/ziPWPjFQ4KQ4s50w84EA8iSq0O8wsmchKyeH1QMFJf2fHuzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T23:38:05Z"
    mac: ENC[AES256_GCM,data:nAlvz2et6Tyz4Na7788T0KUC6Y5Wpa8sigVO1VxzeYC1+Q5JOMzS8tgyrqTao1V0YudLi8SivDc9cXCaIYY94OBNZ9tIaWHrU5fMyiEzRAesB/DLDbGzxM6JzYBq2oziz3pr0n58rat4fMJgThaSEqzW7y1eqiVBSCS5ERncuPU=,iv:iyr3bFbvDswC12CeWFOefAyh5JBuIT/m8o+ooroPqbM=,tag:Zpp21mxsH6WzgCaQAXxz1A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
