services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: always
    ports:
      - "3001:8080"
    volumes:
      - ./config.yaml:/config/config.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
      - "noc-local:host-gateway"
      - "noc-tux:100.91.104.124"
      - "noc-claw:100.95.102.128"
