emby_api_key: ENC[AES256_GCM,data:PBUjFP/BRNTYo5aChAvxwgxTGFxOqt05m/r+/olbjcI=,iv:GLbXB0gtQfoNeFFwCAOzeBvc/T/II25itywxZHVcDbI=,tag:oMrIdytvmxScasKz5ChZbA==,type:str]
jellyfin_api_key: ENC[AES256_GCM,data:v4vJZRM3L2WGYTuI87qatQ7g/SQ/Ak0Cp7cRYNsixCU=,iv:hIhFNxQkzpUX/TcckMElJfRx1VRr0f5j4kiO6b0C5y0=,tag:wyxq3DrMk3vG884w++wSgg==,type:str]
plex_token: ""
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcUlSTU5WSk05UytqNitT
            UzR1a0V1YlVBelNlV1NWZTFXYWExYkpNWjFRClpjb0VxZWR0UTRMMUVyMTFLL3RI
            eVpXUkw5TVhmNGZGVTNyVGpkM2lRRXcKLS0tIG1PVmNvdjA3U3grV0h3cVFJZ2Yv
            VVNSWGx5dEpJQXI5SEU1cmZMOGhWOHcK8Y6lcqIssg6Gd0d/sAfWWFhBeD7NIzCy
            mgui1kVOKM8NOfYvKNkbNPkQfPrdVsSiuYy4x54tkuDQzfOOkXL8TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T13:40:45Z"
    mac: ENC[AES256_GCM,data:ho4XNOS1fljA/8EXj9QNBU275K5f+8HiZlzciMPdY+obMH2KG8tc1ui4Q6usrdrSoUZCWGb5Q5feF4Wl23q1UfLweh5Np8zDH4cTKf8NkQkMpU05inOJRgrljX3qhwsIvHDiFJylBC7pasexWvAF5m5huNLOVDg9NXTFK9EOzbk=,iv:I3z2sBPMJKxUoufmQN2+u/+stPdrViz3cfTTu7NQJng=,tag:VWUKPV2qlwWlQz2qtrNfQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
