emby_api_key: ENC[AES256_GCM,data:M8K7oPGBV+l7+Mzsd5rc/nDzjkq3nvX+zgV2zhqi5ZY=,iv:lPQxi0NnkrMb6RmgQ7TX1j4QA/f9hasmH7tKoeWGCYA=,tag:2quYbtmZgslIKvvRI8/9PQ==,type:str]
jellyfin_api_key: ENC[AES256_GCM,data:6Zybksh11w0WoSDXHyBf4+gqY+vudcU51KzMISY5QT0=,iv:aZdK4pvJiVFFBe1fSLHRyfQTnNUuNhkis8l/iJ3OKdU=,tag:zg79pvPcncdYRjXyn81GtQ==,type:str]
plex_token: ENC[AES256_GCM,data:xY/CS2z9rQhoDDWvqgVWzj/HSBM=,iv:iUvq1arAoAizqkKPqAQ/9PVr9sieAdm3/hjJnuStsVw=,tag:soW7QM1XMv4EsMZ+yWaUwA==,type:str]
sops:
    age:
        - recipient: age1jdd07e42w6hgjncpsz0uxe0nruqgpexsl8nhh2vauwn9w0r53paqm9s87h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRT0Y0WFZqRDJJMXplYmtQ
            dmxKUXhNVWNlQzEwZ0tQNEdTaUVmR0xRbldBCitLblpWTWg3cllUYnA2TzhPTHpm
            cW5vc3VPem9QSk9LaGFESGsxbzJMc1kKLS0tIDkzVTlwemxmZkttc0NOWFkxK2d1
            YTBBTXE2MEVxQi8xVWt3UGZ5VHl6bmMKlr7W6hhBQY1PRjzqCVBNBrKu1apkHW1c
            0016eHrsNf52QskEGhZ9xcdy209vtmZcpo+IpCS+TGLrW+Ol+m9wtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T15:58:01Z"
    mac: ENC[AES256_GCM,data:XFXKDVDAZ8ODAjwyDN/87XNiZpjXbf6omsd/ugyN54qQUfJEVzBsHusgOLM9XBDQSWqOhU4LqJKP4We8pYSd1ccSuGzAMWrDtunKHQcDaM8UHk21pvDbO9TvFAaJc5xsv+9VSE6ZHdIzjPArGhY1wKTzJSi3rP2z0tVkVZPLfhs=,iv:bia4cvo2sYNvLzvoxZfuH/OkwI7eGQofupeD+a20PBU=,tag:9AuQ9h5G1MLpv8Os72SeLg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
